= Add and delete activities, day models, availabilities, and comments
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Manually add or delete activities, day models, availabilities, and comments in your peoples' shifts in Shift Center.
:page-aliases: add-and-delete-items

In {bc-plan-shift-center}, you can manually add and delete the following *entries* to your schedule:

- xref:administration:activities.adoc[Activities]
- xref:administration:daymodel-basics.adoc[Day models]
- xref:administration:availabilities.adoc[Availabilities]
- Comments

New to *Shift Center*? Learn xref:scheduling:shift-center-overview.adoc[the basics] first.

[#level-in-the-schedule-area]
== Levels in the schedule area
You can add different *entries* in the levels in the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area]. Select the levels you want to display in the *schedule area* with xref:scheduling:shift-center-overview.adoc#action-bar[the action bar].

The following table provides an overview of the *entries* you can add to each level:

<style>
   table {
      margin-left: 0px;
   }
   td:nth-child(2), td:nth-child(3), td:nth-child(4), td:nth-child(5) {
      text-align: center;
   }
</style>

[%header, cols="1a,1a,1a,1a,1a,".rstrip(',')]
|===
|Level
|Activities
|Day models
|Availabilities
|Comments
|Actual
|<i class="icon-check">
|<i class="icon-check">
|
|<i class="icon-check">
|Schedule
|<i class="icon-check">
|<i class="icon-check">
|
|<i class="icon-check">
|*Time Recording*
|<i class="icon-check">
|
|
|<i class="icon-check">
|Correction
|<i class="icon-check">
|
|
|<i class="icon-check">
|Request
|
|<i class="icon-check">
|
|<i class="icon-check">
|Alternative Request
|
|<i class="icon-check">
|
|<i class="icon-check">
|*Absence Request*
|<i class="icon-check">
|
|
|<i class="icon-check">
|Availability
|
|
|<i class="icon-check">
|<i class="icon-check">
|External System
|<i class="icon-check">
|
|
|<i class="icon-check">
|Version 1
|<i class="icon-check">
|<i class="icon-check">
|
|<i class="icon-check">
|Version 2
|<i class="icon-check">
|<i class="icon-check">
|
|<i class="icon-check">
|Version 3
|<i class="icon-check">
|<i class="icon-check">
|
|<i class="icon-check">
|===

[#add-activities]
== Add activities
To add activities, follow these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell*.
   The *configuration window* opens in the *Activities* tab.  
   The *Activities* tab displays a table with the scheduled activities, if there are any.
2. Select an activity type from the *Type* drop-down menu.
3. {btn-add}  
   A row for the activity type is added to the table if at least one activity of this type is available. Activities can be unavailable because they are not set up for the selected activity type, they are not assigned to the person's planning unit or because the person does not have the skills required for the activity.
4. Configure the activity in the following columns:
   - *Activity*
   - *Start time*
   - *End time*
   - *-/0/+*: Select the xref:#booking-date-and-columns---0-+[Booking Date], or the previous or following day.

5. {btn-ok}

[#add-multiactivities]
=== Add multiactivities
To add xref:administration:activity-types-and-properties.adoc#subactivities[multiactivities], follow these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell*, and click the *Multi-Activities* tab in the *configuration window*.
   The *configuration window* displays a table with the scheduled multiactivities, if there are any, and a list of multiactivities assigned to the person's planning unit on the right. To see the subactivities assigned to the multiactivity, click the {icon-plus}.
2. Double-click the multiactivity.  
   Rows for the multiactivity are added to the table.
3. Configure the multiactivity in the following columns:
   - *Start Time*
   - *End Time*
   - *-/0/+*: Select the xref:#booking-date-and-columns---0-+[Booking Date], or the previous or following day.

4. Click *OK*.

[#add-full-day-activities]
=== Add full-day activities
If you have xref:administration:activity-types-and-properties.adoc#activity-properties[allowed an activity as a full-day activity], add it by following these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell*, and click the *Full-Day Activities* tab in the *configuration window*.  
   The *configuration window* displays a table with the scheduled *full-day activities*, if there are any. To display all *full-day activities* of the year for the relevant person, check the *Display All Full-Day Activities of the Year* checkbox.
2. Select an activity type from the *Type* drop-down menu.
3. {btn-add}  
   A row for the full-day activity is added to the table.
4. Configure the full-day activity in the following columns:
   - *Activity*
   - *Start Date*
   - *End Date*

5. {btn-ok}

[#add-day-models]
== Add day models
To add day models, follow these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell*, and click the *Day models* tab in the *configuration window*.  
   The *configuration window* displays a table with scheduled day models, and the *Day Models (PU)* and *Day Models (Emp.)* lists with *expandable sections* on the right. The *Understaffed Shifts* and *Generated Shifts* sections include the results of the xref:scheduling:schedules-shift-bidding.adoc#generate-shifts[shift generation]. The other *expandable sections* include day models sorted by abbreviation, time, or duration. To expand the sections, click the {icon-plus} next to them.
2. Click the {icon-plus} next to the day model you want to add.  
   Variable day models display a list of possible times at which you can add them. Fixed day models display only one day model time option.
3. Double-click the day model time.  
   A row for the day model is added to the table. To display the day model details, click the {icon-plus} next to the day model.
4. (Optional) For variable day models, click the cell in the *Start Time* column and set the start time with the drop-down menu. The *End Time* changes according to the duration of the day model.
5. {btn-ok}

[#add-availabilities]
== Add availabilities
To add availabilities, follow these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell* in the *Availability* level row.
   The *configuration window* opens in the *Availability* tab. The *Availability* tab displays a table with the availabilities of the relevant person.
2. Click *Add*.  
   A row for the availability is added to the table.
3. Configure the availability in the following columns:
   - *Start Time*
   - *End Time*
   - *-/0/+*: Select the xref:#booking-date-and-columns---0-+[Booking Date], or the previous or following day.

4. Click *OK*.

[#add-day-model-availabilities]
=== Add day model availabilities
In the xref:#add-availabilities[Availability tab] of the *configuration window*, you can also add availabilites configured as xref:administration:availabilities.adoc#configure-availabilities[day model availabilities]. The *Availability* tab displays the *Day Models (PU)* list with *expandable sections* on the right. The *expandable sections* include day model availabilities sorted by abbreviation or start time. To expand the sections, click the {icon-plus} next to them. To add day model availabilities, follow these steps:

<!-- An availability specifies certain time slots on a day where an employee is available for work. If no availability has been defined, the employee is considered as _available_ for the whole day. -->

1. Click the {icon-plus} next to the abbreviation or start time of the day model you want to add.
2. Double-click the day model availability.  
   A row for the day model availability is added to the table.
3. Configure the day model availability in the following columns:
   - *Start Time*
   - *End Time*
   - *-/0/+*: Select the xref:#booking-date-and-columns---0-+[Booking Date], or the previous or following day.

4. Click *OK*.

[NOTE]
====
If you add a day model availability, it overwrites other availabilities, except other day model availabilities.
====
>
[NOTE]
====
If you add day model availabilities with overlapping time, they are combined into a longer availability with the earliest start time and latest end time.
====
[#add-comments]
== Add comments
In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], you can add comments to each level for each person per day. To add comments, follow these steps:

1. Double-click a *day cell*, and click the *Comments* tab in the *configuration window*.
2. Enter a comment with a maximum length of 250 characters.
3. {btn-ok}  
   The *day cell* you commented is highlighted with a thicker border. To see the comment, hover over the *day cell*.

You can see the comments you add in different parts of Peopleware:

- The xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area] in *Shift Center*
- The xref:scheduling:schedules-overview.adoc#schedule-area[schedule area] in {bc-plan-schedules}
- In xref:me:explore-me.adoc#see-your-schedule-my-calendar[Me] if you add the comment to a day within a scheduling period with the status Published or Shift bidding enabled.

[#add-activities-day-models-availabilities-or-comments-to-multiple-people]
== Add activities, day models, availabilities, or comments to multiple people
You can add the same activity, day model, availability, or comments to the schedule of multiple people at once on the same day. To add the same *entry* to a *day cell* of multiple people, follow these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell* and click the *Employees* tab.
2. Check the checkboxes next to the people for whom you want to add an *entry*. To select or deselect all people, click btn:[All] or btn:[None].
3. Click the tab that corresponds to the *entry* you want to add, e.g. the *Activities* tab.
4. Add an xref:#add-activities[activity], xref:#add-day-models[day model], xref:#add-availabilities[availability], or xref:#add-comments[comment].

[NOTE]
====
Users with Admin access or the *Planner* role can update schedules regardless of any scheduling rule violations. If they update the schedule of multiple people at once, check if any scheduling rule was violated in the xref:scheduling:shift-center-overview.adoc#message-area[message area].
====
[#delete-activities-day-models-availabilities-or-comments]
== Delete activities, day models, availabilities, or comments
In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], you can delete activities, day models, availabilities, or comments, or delete all *entries* of a *day cell*.

[#delete-activities-day-models-or-availabilities]
=== Delete activities, day models, or availabilities
You have two options to delete activities, day models, and availabilities:

- In the *schedule area*: Right-click the *entry* you want to delete in xref:scheduling:shift-center-overview.adoc#day-week-month-and-year-columns[the expanded day cell] and select *Delete Entry*.

- In the *configuration window*:
  1. Double-click the *day cell*.
  2. Select the tab corresponding to the *entry* you want to delete, e.g. the *Activities* tab.
  3. Click the row of the *entry* you want to delete in the table.
  4. Click *Delete*.
  5. Click *OK*.

[#delete-comments]
=== Delete comments
To delete comments, follow these steps:

1.  Double-click the *day cell*, and click the *Comments* tab.
2.  Delete the comment.
3.  Click btn:[OK]

[#delete-all-entries-of-a-day-cell]
=== Delete all entries of a day cell
To delete all *entries* of a *day cell*, right-click the *day cell* and select *Delete All Entries*.

[NOTE]
====
*Entries* are deleted without prior confirmation. To recover deleted *entries*, use the xref:#recover-previous-schedules-states[History tab].
====
[#recover-previous-schedules-states]
== Recover previous schedules states
Whenever you create or update a schedule, or delete *entries*, the schedule state previous to the change is saved in the *History* tab. To recover the schedule state, follow these steps:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], double-click a *day cell*, and click the *History* tab.  
   The *History* tab includes a table with the current schedule on the top and previous schedules states sorted by chronological order.
2. Click the number of the schedule state you want to recover in the *Layer* column.  
   The schedule state is replicated above the current schedule.
3. {btn-ok}

[#booking-date-and-columns---0-+]
== Booking date and columns -/0/+
The *Activities*, *Multi-Activities*, and *Availability* tabs of the *configuration window* include tables with a *Booking Date* column and configurable *-/0/+* columns. The *Booking Date* and *-/0/+* columns function as follows:

- *Booking Date*: Indicates the date of the *day cell* you clicked to open the *configuration window*.

- *-/0/+*: Set the start or end time of the activity or availability to the *Booking Date*, or to the previous or following day. The first *-/0/+* column refers to the start time and the second refers to the end time. Select one of the options:
  - *-*: Set the start or end time to the day before the *Booking Date*.
  - *0*: Keep the start or end time on the *Booking Date*.
  - *+*: Set the start or end time to the day after the *Booking Date*.