= Find replacement people for activities, full days or understaffed shifts
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Find people to cover absences or understaffed shifts. Learn also how to exchange shifts between two people.
:related-articles: use-keyboard-shortcuts.adoc, shift-center-overview.adoc

If a scheduled person cannot perform a certain activity or shift or cannot work for a full day (e.g. due to sick leave), you may need to find a person to replace them, or exchange their shift with another person. In {bc-plan-shift-center}, you can perform the following actions:

- Schedule a replacement for a certain activity or shift or for a full day
- Find people for understaffed shifts
- Exchange activities and shifts between two people

New to Shift Center? Learn xref:scheduling:shift-center-overview.adoc[the basics] first.

[#find-a-replacement-person]
== Find a replacement person
To find a replacement person, proceed as follows:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], click a day column header.
2. In the row corresponding to the person you want to replace, proceed as follows:
   - To find a replacement for an activity, right-click an activity and select *Find replacement employee*.
   - To find a replacement for the entire day, right-click a day cell and select *Find replacement employee for day...*.

3. In the window that opens, you can see a list of people with skills matching the activities. To filter the results, click the *Options* tab:
   - In the *Selections* row, select one of the following options:
     - *Ignore*: Show people from all selections
     - *Observe*: Show only people that belong to the same selection(s) as the person
   - In the *Placements* row, select one of the following options:
     - *Ignore*: Show people regardless of their scheduled activities or shifts.
     - *With the same working hours and the same date*
     - *At least one placement on the same scheduled day*: Show people with scheduled activities on that day
     - *No placement on the same scheduled day*: Show people with no scheduled activities on that day

4. Click the *Replacement Employee* tab. The list shows the people matching your criteria.
5. Click the person you want to schedule as a replacement.
6. {btn-ok}

If the action does not violate any scheduling rule, people's schedules are updated accordingly.

[#find-people-for-understaffed-shifts]
== Find people for understaffed shifts
To find a person for an understaffed shift, proceed as follows:

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[parameter area], click the *Day Models* tab.
2. Right-click a cell and select *Find Employees for Shift...*.
3. In the window that opens, you can see a list of people with the necessary skills. To filter the results, click the *Options* tab and select one of the following options in the *Placement* row:
   - *Ignore*: Show people regardless of their scheduled activities or shifts.
   - *None on the same booking day*: Show only people who are not scheduled on that day.
4. Click the *Employees* tab and select a person.
5. {btn-ok}
   If the action does not violate any scheduling rule, people's schedules are updated accordingly.

[#exchange-shifts-between-two-people]
== Exchange shifts between two people
You can exchange all activities and shifts of a given day between two people.

1. In the xref:scheduling:shift-center-overview.adoc#schedule-area[schedule area], click a day column header.
2. Right-click a day cell.
3. Select *Find Exchange Partner...*.
4. In the window that opens, a list of people with the necessary skills and contract parameters appears. To filter the results, click the *Options* tab:
   - In the *Selections* row, select one of the following options:
     - *Ignore*: Show people from all selections
     - *Observe*: Show people that belong to the same selection(s) as the person
   - In the *Placements* row, select one of the following options:
     - *Ignore*: Show people regardless of their scheduled activities or shifts.
     - *With the same working hours and the same date*
     - *At least one placement on the same scheduled day*: Show people with scheduled activities on that day
     - *No placement on the same scheduled day*: Show people with no scheduled activities on that day

5. Click the *Find Exchange Partner* tab and select a person.
6. {btn-ok}

If the action does not violate any scheduling rule, people's schedules are updated accordingly.