= Save staff requirements
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-task:
:description: Learn how to make a workload's staff requirement data available for scheduling.
:related-articles: concept-staff-requirements.adoc, task-set-up-staff-requirement-calculation.adoc, task-run-requirement-calculations.adoc, ref-requirement-calculations.adoc

This article explains how to save staff requirement data that Peopleware calculated automatically based on a workload's forecast data.
Saving staff requirement data makes that data available for scheduling processes.

[#use-staff-requirements-for-scheduling]
== Prerequisites
[#general]
=== General
Peopleware calculate staff requirement data automatically for all forecast versions of a workload if the following conditions are met:

- Staff requirements calculation is set up for the workload.
- The business hours settings specified for the planning unit are valid in the calculation period.
- The activity's validity period covers the calculation period.

[#permissions]
=== Permissions
Your role needs to have object permissions for the objects associated with the action:

- The workload for which staff requirements are calculated.
- The planning unit and activity specified in the workload's staff requirements calculation settings.

[%header, cols="1a,1a,".rstrip(',')]
|===
|Object type
|Permissions
|Workload
|View
|Planning unit
|View
|Activity
|View
|===

[NOTE]
====
====
>
[NOTE]
====
Object permissions for workloads are set up in _Account > Roles_{:.breadcrumbs}.<br>
Object permissions for planning units and activities are set up in _WFM > Administration > System > Role Authorization_{:.breadcrumbs}
====
[#steps]
== Steps
[NOTE]
====
====
>
[NOTE]
====
- Saving staff requirements overwrites existing data.
- You cannot save staff requirements for parent planning units.
====
1. In _Forecast > Workloads_{:.breadcrumbs}, select a workload.
2. Select a period with the date picker. Peopleware will save the staff requirement data for this period.
3. In the **Staff requirements** section, select a forecast version from the **Basis for the staff requirements calculation** drop-down field.
4. Click _Save staff requirements_{:.doc-button}.
5. In the **Save staff requirements** window, click _Save_{:.doc-button}.

Peopleware saves the staff requirements for the planning unit and activity specified in the staff requirements calculation settings and the period that you selected on the workload page.
The staff requirements are available for scheduling tasks, e.g. in _Plan > Schedules_{:.breadcrumbs}.
You can check the calculation results in _Plan > Schedules_{:.breadcrumbs} and _Plan > Shift Center_{:.breadcrumbs}.