= Run staff requirement calculations
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-task:
:description: Learn how to run staff requirement calculations in Peopleware.
:related-articles: concept-staff-requirements.adoc, task-set-up-staff-requirement-calculation.adoc, ref-requirement-calculations.adoc

This article describes how to run the manual calculation of staff requirements.

[#prerequisites]
== Prerequisites
[#prerequisites]
=== General
{prereq-intro}

- You have clicked *Use forecast* to ensure your latest forecast is being used for staff requirement calculation.

[#permissions]
=== Permissions
Your role needs to have the following object permissions:

- View permission for the relevant workloads
- View permission for the relevant planning units
- View permission for the relevant activities
- View permission for the relevant queues for calculations that need to read data from a source queue
- Edit permissions for the relevant queues for calculations that need to write read data to a target queue

Your role needs to have the following functional permissions:

- Full access to requirement calculations under *Forecast*.

[#run-a-requirement-calculation]
== Run a requirement calculation
Each requirement calculation has its own configuration interface and parameters, but the general process is the same.

1.  Go to {bc-forecast-requirement-calculations}.
2.  Select the calculation you need from the list to open it.
3.  (Optional) Click btn:[Apply preset...] and select a preset from the list.
4.  In the *Calculation parameters* section, configure the specific parameters for the calculation, e.g. date ranges, planning units, activities, and service goals.
5.  Click btn:[Run].

Peopleware saves the staff requirements for the planning unit and activity in {bc-plan-schedules}.