= Combine scheduling methods
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Combine the different scheduling methods to meet your business demands.
:related-articles: scheduling-methods.adoc, shift-sequences.adoc, availabilities.adoc, work-time-pattern-models.adoc

You can combine all xref:scheduling:scheduling-methods.adoc[scheduling methods] in many ways to create schedules that balance the needs of your people and those of your business.

The following examples show some common use cases for combining scheduling methods. You can also use other scheduling methods combinations to best meet the needs of your organization.

[#use-case-1-people-with-flexible-shifts-plus-people-with-specific-working-hours-or-days]
== Use case 1: People with flexible shifts plus people with specific working hours or days
For this use case, you can combine fixed scheduling with either rotating flexible shifts, or fully flexible shifts.

To plan your people using this combination, you first need to configure the configuration data shown in the following table, and assign it to the relevant people:

[%header, cols="1a,1a,".rstrip(',')]
|===
|People with flexible shifts
|People with specific working hours or days
|Assign the work time pattern models you want to use to them.
|Create specific shift sequences defining the hours or days when they should work, and leave the rest of the week blank. +Assign the shift sequence and the relevant work time pattern models to them.
|===

To schedule your people, follow these steps:

1. Insert your shift sequences.
2. Use the *Create optimized schedule* functionality. +
Your rotating and fully flexible shifts are scheduled in a way that complements the coverage provided by the shift sequences.

[#use-case-2-people-with-rotating-shifts-plus-people-with-flexible-shifts]
== Use case 2: People with rotating shifts plus people with flexible shifts
For this use case, you can combine rotating flexible shifts and fully flexible shifts.

To plan your people using this combination, you first need to assign the configuration data to the relevant people, as shown in the following table:

[%header, cols="1a,1a,".rstrip(',')]
|===
|People with rotating flexible shifts
|People with fully flexible shifts
|Assign work time pattern models of type B or D to them.
|Assign work time pattern models of type A to them.
|===

Use the *Create optimized schedule* functionality. +
People with rotating flexible shifts will be assigned the rotation defined by their work time pattern models, and people with fully flexible shifts will fill up the rest of the schedule.

[#use-case-3-people-with-rotating-shifts-and-restricted-availability]
== Use case 3: People with rotating shifts and restricted availability
This use case refers to people who work rotating shifts but are not available at specific times, e.g. they cannot work past 5 PM on Wednesdays.

For this use case, you can combine availabilities and rotating flexible shifts.

1. Configure xref:administration:availabilities.adoc[availabilities] for your people that define when they cannot work. In this case, they are available on Wednesdays only until 5 PM.
2. Assign to them the relevant work time pattern models.

For weeks when the person works the morning shift, they will be scheduled on Wednesday. +
For weeks when the person works the evening shift, they will not be scheduled on Wednesday, and they will be planned for other days of the week.

[#use-case-4-people-with-fixed-shifts-and-punctually-restricted-availability]
== Use case 4: People with fixed shifts and punctually restricted availability
This use case refers to people who work fixed shifts but have a more restricted availability on some particular days, e.g. they work night shifts, or during the weekend, but only every other week.

For this use case, you can add xref:administration:daymodel-basics.adoc#types-of-day-models[day models of the type Availability] to xref:administration:shift-sequences.adoc[shift sequences] to influence the scheduling result on particular days. +
See the two examples below.

To plan people to work shifts every other weekend, follow these steps:

1. Create a day model of type Availability with a time range from midnight (0:00) to 0:01 AM as a blocker.
2. Add the day model to one weekend in a shift sequence with 14 days, and leave all other days blank.
3. Assign the shift sequence to the relevant people.
4. Insert the shift sequence into your schedule.
5. Use the *Create optimized schedule* functionality.

Every other weekend, no shifts are scheduled and the remaining days are optimized accordingly.

To plan people to work night shifts every other week, follow these steps:

1. Create a day model of type Availability with a time range from midnight (0:00) to noon (12:00).
2. Add the day model to each day of a week in a shift sequence with 14 days, and leave all other days blank.
3. Assign the shift sequence to the relevant people.
4. Insert the shift sequence into your schedule.
5. Use the *Create optimized schedule* functionality.

In the weeks when people are available, the night shift is scheduled following the work time pattern model assigned to each person.

In the other weeks, any shift that complies with the work time pattern model can be scheduled.