= Duplicate objects
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise, classic
:topic-type-concept:
:description: Duplicate objects to create similar objects with shared properties.

In menu:Plan[Configuration], you can duplicate configuration objects, such as activities, day models, contracts, week time patterns or work time pattern models.
This allows you to create configuration objects faster.

Duplicating a configuration object includes its assigned objects, for example planning units.

[NOTE]
====
Duplicating an activity does not include its assigned objects.
====
== Prerequisites

=== Permissions

{role-needs-permissions}

- *Access to Plan Configuration*
- *Create* permission for the object type you want to duplicate.

Your role needs object permissions for the object you want to duplicate and its assigned objects.

== Steps

1. Go to menu:Plan[Configuration].
2. Select an object type, e.g. activities, day models or week time patterns.
3. In the row of the object you want to duplicate, click the contextual menu {icon-context-menu}.
4. Click *Duplicate*.

The configuration page for the duplicated object opens immediately.
Peopleware adds a number in brackets to the original name.
Example: The copy of the Calls activity becomes Calls(1).
You can configure the duplicated object as needed.