= Intraday adherence
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Get an overview of how closely people have adhered to their shift schedules throughout the day.
:related-articles: real-time-adherence.adoc, edit-intraday-activities.adoc

In menu:Intraday[Intraday Adherence], you can compare people's scheduled activities with the actual activities to identify out-of-adherence periods throughout the day. Intraday adherence uses xref:intraday:real-time-adherence.adoc[real-time adherence] data from your ACD or the Time Tracking app in Me. You can access the adherence data for the current month and the last six months.

[#display-data]
== Display data
To display adherence data for a specific day, follow these steps:

1. Select a *Planning unit* and/or a *Selection*.
2. At the top of the page, select a date by using the date picker, or click btn:[Today] or btn:[Yesterday].

The page displays the total adherence score, adherence scores by interval, and a table with the details of the adherence data per person for the selected day.

[#adherence-score]
=== Adherence score
The page shows different adherence score details:

- *Adherence*: Percentage of working time spent on scheduled activities. If the day has not ended, the score is calculated up to the last updated timestamp, which is displayed above the score. If the score falls below the xref:intraday:real-time-adherence.adoc#target-adherence-score[the target adherence score], it is highlighted in red.
- *Scores by interval*: Vertical blue bars represent scores by interval. Scores lower than 100 % represent intervals during which people’s actual activities deviate from their scheduled activities.
- *Target adherence score*: The dashed line in the graph shows the configured target score.



[#staff-overview-table]
=== Staff overview table
Under the total adherence score and the scores by interval, a table displays adherence details for the selected day. To sort the table by adherence score, click the *Adherence* header. To sort the table by name, click the *Name* header.

Each row shows a person's adherence score. Differences between the person's scheduled activities and their actual activities are highlighted.

When a person's score drops below the configured adherence target score, their score is highlighted in red. xref:intraday:adherence-matches.adoc[Matches] and xref:intraday:real-time-adherence.adoc#buffer-time[buffer times] may influence changes in status and adherence types. Learn more about the xref:intraday:real-time-adherence.adoc#adherence-statuses[status and types].

Different colors identify the three out-of-adherence types:

- Red: Not present
- Yellow: Wrong activity
- Blue: Not scheduled

[#agent-intraday-adherence]
== Agent intraday adherence
To see the details of a person's intraday adherence in a new window, click their row. To change dates, use the month selector or the navigation arrows next to the dates.

On the left, two boxes display an overview of the selected month:

- *Person name*: Shows the person's adherence score, how long they were scheduled, and adherence details for the selected month. The values include the data up to the last completed interval of the current day.
- *Daily overview*: Days for which adherence scores are available are highlighted in red. Hover over a date to see the adherence score of the selected person. Click a date to see the details.

On the right, you can see in detail when this person was scheduled and where they did not adhere to the schedule:

- *Intraday adherence score*: Calculated using data up to the last completed interval of the current day. Identical to the day score when you hover a date in *Daily overview*.
- *Scheduled* and *Out of Adherence* durations: Sum of durations for all scheduled activities (activity types Present, Meeting, Break) and deviations in the schedule on the selected date.
- *Timeline*: Colored bars highlight scheduled activities, actual activities, and out-of-adherence statuses. In the *Out of adherence* row, you can click out-of-adherence time slots to zoom in. Click btn:[Reset zoom] to reset the zoom.
- *Table*: Each row shows details for out-of-adherence periods. Click a header to sort data by time period, actual activity, status, scheduled activity or out of adherence duration.

[#adherence-report-csv-file]
== Adherence report (CSV file)
If you need to analyze adherence and conformance data for individual people over a longer time frame, e.g. to calculate bonus payments, you can download a report as a CSV file that includes aggregated adherence and conformance data. To download the Adherence report file , follow these steps:

1. Select a *Planning unit* and/or a *Selection*.
2. Click btn:[Download report].
3. In the *Download report* window, select a date range for the report. You can select any date range from one day to up to six months in the past.
4. Click btn:[Download report].

The table below explains the report columns:

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|Column
|Explanation
|Calculation
|Activity
|The activity for which the adherence data is displayed.
|--
|Scheduled minutes
|The duration scheduled for the activity, in minutes.
|--
|Actual minutes
|The actual time spent on the scheduled activity, in minutes.
|--
|Minutes in adherence
|Time spent in activities that comply with the scheduled activities
|--
|Minutes out of adherence
|Time spent in activities that do not comply with the scheduled activities
|--
|Adherence in %
|Percentage of working time spent in activities that comply with the scheduled activities
|Minutes in adherence/scheduled minutes \* 100%
|Minutes out of conformance
|The difference between the actual working time and the scheduled time
|Actual working minutes - scheduled minutes
|Conformance in %
|Percentage of working time in compliance with the scheduled working time
|Actual time/scheduled time \* 100%
|Scheduled in %
|The percentage of scheduled working time for an activity of a certain type
|Scheduled time for the relevant activity type/total scheduled time \* 100%
|Actual in %
|The percentage of actual working time spent on an activity of a certain type
|Actual time for the relevant activity type/total actual time \* 100%
|===

Each row of data includes a link to display the related data in menu:Intraday[Intraday Adherence].

[#frequently-asked-questions]
== Frequently asked questions
[%header, cols="1a,1a,".rstrip(',')]
|===
|Question
|Answer
|Why are some or all people missing?
|Try to clear the search input. Check if the people you are looking for are scheduled today in the selected planning unit or selection.
|Why can't I select a specific date?
|You can access historical adherence data for the six months prior to the current date, plus the current month (e.g. if today is July 15, you can select dates between January 1 and July 15.)
|Which time zone does Intraday adherence use?
|Intraday adherence uses the selected planning unit's time zone. If you click a person to see the Agent Intraday Adherence details, all times appear in the *time zone* configured in your user profile. The time zone is displayed at the top right of the adherence timeline.
|===