= Map external statuses to activities
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: None
:related-articles: import-agent-status-data.adoc, activities.adoc

New to real-time adherence? Learn xref:intraday:real-time-adherence.adoc[the basics] first.

The real-time adherence feature uses data from your external system (usually an ACD) about what your people do when they are at work. This data is imported directly from your ACD after you have set up an integration.

In order to monitor your people's adherence to their schedule, you need to map the statuses your ACD uses (here called external statuses) to your activities in Peopleware.

Go to {bc-intraday-configuration} to map external statuses to activities.

[#mapping-strategies]
== Mapping strategies
How you map external statuses to activities will depend on your monitoring needs.

Imagine your ACD uses these three statuses: waiting for call, on a call, and after-call work. In Peopleware, you schedule the activity Calls. There are two strategies that you can follow, depending on the level of detail that you need:

Option A: You want to monitor how well your people adhere to their scheduled activities. In this case, you can map all three external statuses to the activity Calls. This way, whenever your people have any of those three statuses in the ACD, Peopleware shows that they are doing calls, and compare that activity to their schedule.

Option B: You want a higher level of detail in your adherence monitoring. You want to know how much time your people spend waiting for a call, actually being on a call, and doing after-call work. In this case, you would create three additional activities corresponding to the three external statuses, and xref:intraday:adherence-matches.adoc[match] the three new activities to the activity Calls. You can then map each external status to its corresponding activity.

[#map-external-statuses-to-activities-in-intraday]
== Map external statuses to activities in Intraday
1. In {bc-intraday-configuration}, select an activity from the list.<br>Under **Integrations**, you will see a list of your integrations.
2. Click the integration with the system whose external statuses you want to map.<br>In the **External statuses** section, you can find all statuses from the external system.<br>If a status is already mapped to an activity, the activity's name is displayed next to it.
3. Select all external statuses you want to map to that activity.
4. Click btn:[Save changes].

You can use the search field to search external statuses by name, or you can enter "unmapped" to see all statuses from the selected integration that are not yet mapped to any activity.

[#map-external-statuses-to-activities-in-wfm]
== Map external statuses to activities in WFM
If you do not have access to {bc-intraday-configuration}, integrations store such activities in the activity Present (ID 1) and display the imported agent status as Present. To display the same activities as your external system, you first need to pause the integration:

1. {nav-to-account-integrations}
2. In the list of integrations, click the Suspend importing icon {icon-pause-circle} next to the integration for which you want to remap external statuses.

You can then remap external statuses to other activities as follows:

1. Go to {bc-plan-config-activities}.
2. Select the activity you want to remap.
3. In the **External Systems** section, click btn:[Edit in WFM].
4. Scroll down to the **External Systems** section and click the {icon-wfm-delete} next to **Present**.
5. In the **External Systems** section, click the Add icon {icon-wfm-add}.
6. In the **External Systems** window, configure the following:<br>
   - **External System**: Select the relevant integration.
   - **Name from the External System**: Select the activity from the external system that you want to map to the currently selected Peopleware activity.
   - **Classification**: Select the value 1.
7. {btn-ok}

[#remap-already-mapped-external-statuses]
== Remap already mapped external statuses
You can map an already mapped external status to another activity.

1. In {bc-intraday-configuration}, select an activity, and then an integration.
2. In the **External statuses** section, select the external statuses that you want to remap.<br>You will see a yellow warning icon next to the name of the activity to which the external status is currently mapped.
3. Click btn:[Save changes].<br>The previous mapping is overwritten.