= Migrate your database to unicode
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: on-premise
:topic-type-concept:
:description: Learn how to migrate your injixo Enterprise on-premise database to Unicode encoding (utf-16).

As of build 9001, Unicode encoding of the database is mandatory. Also older injixo versions may already use Unicode. Check your database encoding before an update and convert the database from ANSI to Unicode if necessary.

[#check-database-encoding]
== Check database encoding
Run the following SQL statement on your database:

`SELECT vs_version_no, encoding FROM vs_version;`

If the result is `utf-8` or `utf-16`, you are already using Unicode. If an ISO character set appears, e.g. `ISO-8859-1`, migrate the database.

[IMPORTANT]
====
: To avoid losing production data, create a backup before migrating data.
====
[#preparation]
== Preparation
Download the link:https://downloads.injixo.com/_downloads/db-scripts-and-tools/injixo%20Enterprise%20DB%20scripts.zip[database scripts]. The folder contains all available scripts. You can find out which scripts you need to use below.

[#-migrate-microsoft-sql-server-databases-in-place]
=== ## Migrate Microsoft SQL Server databases in-place
The in-place migration in SQL Server changes all the _VARCHAR_ fields to _NVARCHAR_ fields:

1. Stop the injixo/InVision services.
2. Run the following script: *mssql/migration/conv_unicode_306.sql*.
3. Restart the services.

[#oracle-character-set-migration-by-exportimport]
=== Oracle: Character Set Migration by Export/Import
You can use the Oracle programs exp/expdp or imp/impdb for character set conversion. The import utilities automatically perform the necessary conversions.

[NOTE]
====
Oracle: Is your National Character Set AL16UTF16?
====
>
[NOTE]
====
You will need a new database if the current database does not use AL16UTF16 as National Character Set. This is how you check the National Character Set of your database:
`select * from nls_database_parameters where parameter='NLS_CHARACTERSET' or parameter 'NLS_NCHAR_CHARACTERSET';`
====
This is how you perform the data conversion:

1. Stop the injixo/InVision services.
2. Export your current database using the Oracle export utility (exp/expdp), for example:
   `expdp system/password@db schemas=ISPS directory=TEST_DIR dumpfile=scott_data.dmp logfile=expdp.log content=DATA_ONLY`
3. Create a new Oracle schema, e.g. ISPS2.
4. Run the following script to create the required injixo tables in the new schema: *oracle/create/create-tables.sql*.
5. Import the exported database into the new database using Oracle's impdp, for example:  
   `impdp ISPS2/tiger@db10g schemas=SCOTT directory=TEST_DIR dumpfile=SCOTT.dmp logfile=impdp.log IGNORE=Y`
6. Run the following script for the new schema (ISPS2): `update vs_version set encoding='utf-16';`
7. Restart the services.



[#change-database-connection]
== Change database connection
After the successful Unicode conversion, you may need to connect your Enterprise Server to the new database/schema. To do this, modify the connection string in the *[InVision General Model Settings]* section of the *isps.cfg* file in the installation directory.

----

```