= Update from version 2012.3 or later
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: on-premise
:topic-type-concept:
:description: Learn how to update your injixo Enterprise on-premise server to the latest version if you are currently on version 2012.3 or later.
:page-aliases: update-from-9xxx

This article explains how to update the injixo Enterprise Server. Depending on the version or builds you are currently using, different steps may be necessary for an update. These are described in detail in the following instructions.

[#download-the-current-build]
== Download the current build
Download the current link:https://downloads.injixo.com/en#server-on-premise[injixo Enterprise on-premise version].

[#create-a-backup]
== Create a backup
It is best to make a backup of the database and the installation folder before you perform the update.

[#stop-the-services]
== Stop the services
Stop on your server the *injixo Enterprise* service and if necessary *InVision Enterprise WFM AutoScheduler* and *ISPS Xlink*.

[IMPORTANT]
====
clue!
====
>
[NOTE]
====
Under certain circumstances the Windows service is named *InVision Enterprise WFM*. In this case you should delete the service with the Windows command `sc delete "InVision Enterprise WFM"`. Then go to the injixo Enterprise Server folder on the command line (by default `C:\Program Files\injixo Enterprise Server\Server`) and run the command `isps_r464.exe -install --name "injixo Enterprise Server" --fullname "injixo Enterprise Server"`.
====
[#remove-old-modules]
== Remove old modules
There may still be old modules in your installation. These can lead to the injixo Enterprise Server not starting after the update.
Therefore, if available, delete the file `ivDc64.ivm` in the server directory during the first update.

[#delete-calendar-templates]
== Delete calendar templates
This update includes new holiday templates for the planning calendar. If you are using a build older than 9129, you will need to delete the existing calendar templates to avoid duplicate calendar templates.

In the server directory, in the *auxiliary* folder, delete the *calendar* folder.

Once you have done this step, you can skip it next time. If you are unsure, delete the files if in doubt.

[#copy-the-new-files]
== Copy the new files
Unpack the zip file of the update in the *Server* folder in the directory where you installed the injixo Enterprise Server (by default `C:\Program Files\injixo Enterprise Server\Server`). Please overwrite any existing files.

[NOTE]
====
New Builds (> 9737) require the installation of the _Microsoft Visual C++ 2010 Redistributable Package (x64)_ (link:https://www.microsoft.com/en-us/download/details.aspx?id=26999[Microsoft download]).
====
[#start-the-services]
== Start the services
To complete the update process, start the *injixo Enterprise WFM* service on your server and if necessary *InVision Enterprise WFM AutoScheduler* and *ISPS Xlink*.