= Browser setup
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: on-premise, classic
:topic-type-concept:
:description: Learn how to set up your browser to work with Peopleware.
:related-articles: client-installer-errors.adoc, session-timeout-message.adoc
:page-aliases: setup-guide

To work with ActiveX-based features in WFM, use xref:support:configure-edge-internet-explorer-mode.adoc[Microsoft Edge in Internet Explorer (IE) mode]. You can find a list of compatible browsers in the xref:getting-started:system-requirements.adoc#browser-requirements[System requirements].

If you have insufficient rights to change the browser settings or to install software, contact your IT department.

[#configure-the-trusted-sites-and-security-zone-settings]
== Configure the trusted sites and security zone settings
Classic and Enterprise WFM contain ActiveX controls. You need to allow the browser (Edge in IE Mode) to run these ActiveX controls.

In the browser settings, add all Peopleware pages (_\*.peopleware.com_) to the trusted sites:

1. Open the Windows start menu, type internet options, and press the Enter key.
2. On the **Security** tab, select the **Trusted sites** zone, and click btn:[Sites].
3. In the **Add this website to the zone** field, enter https://\*.peopleware.com.
4. Check the checkbox **Require server verification (https:) for all sites in this zone**.
5. Click **Add**.
6. Click **Close**.

{{ 1 | image: 'security settings', '45%', 'jpg' }}

Adjust the security zone level for the trusted sites:

1. On the Windows start menu, type internet options, and press the Enter key.
2. On the **Security** tab, select the **Trusted sites** zone.
3. Uncheck the checkbox **Enable Protected Mode**.

   Note: This checkbox is no longer available in Windows 11 and above.

4. On the **Security** tab, adjust the security level for **Trusted Sites** to **Medium** or **Medium-Low**. Medium-Low allows you to skip steps 6 to 9.
5. {btn-ok}
6. Click btn:[Custom level...].
7. In the **Security Settings** dialog window, change the following settings:

[%header, cols="1a,1a,".rstrip(',')]
|===
|Setting
|State
|Script ActiveX Controls marked safe for scripting
|ENABLED
|Run ActiveX Controls and Plugins
|ENABLED
|Download Signed ActiveX Controls
|PROMPT or ENABLED
|Automatic Prompting for ActiveX Controls
|ENABLED
|===

8. {btn-ok}

   The following message appears: Are you sure you want to change the settings for this zone?

9. Click btn:[Yes].
10. To close the dialog window, click btn:[OK].

[#peopleware-client-installation]
== Peopleware client installation
Classic and Enterprise WFM contain ActiveX controls, which require xref:support:configure-edge-internet-explorer-mode.adoc[Microsoft Edge in IE mode] and the Peopleware client.

If you see an error message <!-- Add message after it has been changed in Peopleware? --> when logging in or within Peopleware:

- use a xref:getting-started:system-requirements.adoc#browser-requirements[compatible browser].
- install the Peopleware client (as described below).

[#automatic-client-installation-wfm-start-page]
=== Automatic client installation (WFM start page)
If you are using the above browser settings, the client installs itself automatically when WFM is entered.

1. Go to *WFM*.
2. Wait until the download has finished and the client installation starts.
3. The browser shows this message: This webpage wants to run the following add-on: 'Peopleware Enterprise' from 'InVision AG'.<br>If the prompt does not appear, ask your IT for help.
4. Click btn:[Install] to install the required add-ons.
5. Click btn:[Install] to install the client.

After successful installation, you can access ActiveX components.

[#manual-client-installation]
=== Manual client installation
Install the client manually, e.g. in WFM Enterprise on-premise or when the automatic installation does not work.

Note: If you are using a software distribution tool, run the installer for the user who will be logged in to the computer later, e.g. using Microsoft's msiexec.exe with the runas /user option.

1. Download the [latest Peopleware client](https://downloads.peopleware.com/en#client-components).
2. To run the MSI installer, click btn:[Run].
3. To continue, click btn:[Next].
4. (Optional) Edit the installation path.
5. If the computer is shared by several users, select **Everyone**.
6. To continue, click btn:[Next].
7. To start the installation, click btn:[Install].
   The following message appears: Do you want to allow the following program from an unknown publisher to make changes to this computer?
8. Click btn:[Yes] to confirm the message.

After successful installation, you can access ActiveX components.