= System requirements
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Browser and desktop requirements for integrations, agents, and planner workstations.
:related-articles: browser-setup.adoc

Peopleware is a browser-based workforce management SaaS software, available in multiple [WFM plans](https://www.peopleware.com/pricing): Essential WFM, Advanced WFM, and Enterprise WFM.

[#browser-requirements]
== Browser requirements
We support the two latest versions of the following browsers:

- Microsoft Edge
- Google Chrome
- Mozilla Firefox
- Apple Safari

[#pop-up-blocker]
== Pop-up blocker
We use pop-ups to display additional dialog boxes. To allow pop-ups for Peopleware, proceed as follows:

- Turn off your pop-up blocker in [Microsoft Edge](https://support.microsoft.com/en-us/microsoft-edge/block-pop-ups-in-microsoft-edge-1d8ba4f8-f385-9a0b-e944-aa47339b6bb5).
- Set a pop-up blocker exception in [Google Chrome](https://support.google.com/chrome/answer/95472?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Callow-pop-ups-and-redirects-from-a-site), [Mozilla Firefox](https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting), and [Apple Safari](https://support.apple.com/guide/safari/block-pop-ups-sfri40696/mac).

[#microsoft-edge-in-internet-explorer-ie-mode]
== Microsoft Edge in Internet Explorer (IE) mode
ActiveX-based features in WFM require xref:support:configure-edge-internet-explorer-mode.adoc[Microsoft Edge in IE mode]. To configure the IE mode, you need a [site list XML file](https://learn.microsoft.com/en-us/deployedge/edge-ie-mode-local-site-list).

<style>
table {
  width: 100%;
}
table th:first-of-type {
    width: 30%;
}
table th:nth-of-type(2) {
    width: 70%;
}
</style>

[%header, cols="1a,1a,".rstrip(',')]
|===
|WFM plan
|Microsoft Edge in IE mode required
|Essential WFM
|No
|Advanced WFM
|No
|Enterprise WFM
|Only when using custom features
|Classic <sup>1</sup>
|Yes
|Enterprise WFM on-premise <sup>1</sup>
|Yes. If not configured, you cannot log in.
|===

<sup>1</sup> Legacy software (old WFM plans that are currently still in use)

If you use the wrong browser or a wrong IE mode configuration, the IE logo in the WFM navigation identifies the features that require IE mode (Classic/Enterprise WFM).

xref:me:configure-me.adoc[Me] works with any listed browser, on computers, smartphones, and tablets.

[#peopleware-client-software]
== Peopleware client software
ActiveX-based features in the WFM require the xref:getting-started:browser-setup.adoc[Peopleware client].

You can find the operating system requirements in the download description under [downloads.peopleware.com](https://downloads.peopleware.com).

[%header, cols="1a,1a,".rstrip(',')]
|===
|WFM plan
|Peopleware client required
|Essential WFM
|No
|Advanced WFM
|No
|Enterprise WFM
|Only when using custom features
|Classic
|Yes
|Enterprise WFM on-premise
|Yes. If not installed, you cannot log in.
|===

If the client is not installed, the IE logo in the left navigation identifies the features that require IE mode (Classic/Enterprise WFM).

xref:me:configure-me.adoc[Me] does not require the Peopleware client.

[#firewall-exceptions]
== Firewall exceptions
To access the web pages, allow web traffic to and from \*.peopleware.com via port 443.

If you use ActiveX-based features or custom SDK applications, add another firewall exception. These applications use port 45054 for outgoing traffic (port 80 for hosts prior to 2019) and require direct Internet access over Transmission Control Protocol (TCP). Proxy servers configured in the browser are not supported.

To get the address for the firewall exception, click _WFM_{:.menu-item} and use the name of your Peopleware host that is visible in the browser address bar, e.g. wfm-123abc.peopleware.com.

To learn more about firewall exceptions in Windows, see [Microsoft documentation](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#:~:text=Go%20to%20Start%20%3E%20Settings%20%3E%20Update,%2C%20file%20types%2C%20or%20process).

[#share-urls-for-websockets]
=== Share URLs for WebSockets
We use WebSockets to send real-time updates to users in Shift Center, Schedules, and Real-Time Adherence.

The TCP-based secure WebSocket protocol allows faster transmissions than HTTP through port&nbsp;443. The browser upgrades a standard HTTP connection to a WebSocket connection. If successful, the browser’s dev tools will show the corresponding HTTP 101 (Switching Protocols) status code when you load the page.

Shift Center requires WebSockets to work at maximum speed. If WebSockets are not available, AJAX polling is used instead. The other pages do not provide a fallback mechanism and show error messages or reconnection attempts if the WebSocket connection cannot be established.

To allow WebSockets connections, add the following URLs to the allowlist of your firewall:

- https://shiftcenter.peopleware.com
- wss:// shiftcenter.peopleware.com
- https://www.peopleware.com
- wss://ws.peopleware.com

[#websockets-and-proxy-servers]
=== WebSockets and proxy servers
WebSockets rely on a persistent TCP connection. Unlike traditional HTTP requests, a WebSocket connection remains open once established. Make sure that your proxy server does not terminate such TCP connections. Popular proxy servers like Nginx or Apache have specific modules or directives to support WebSocket connections.

[#network-bandwidth-requirements]
== Network bandwidth requirements
Peopleware is designed and optimized for high performance and low resource consumption. During the first access, graphics are downloaded and stored locally in temporary files. Afterward, only basic information is transferred securely to the desktop.

A contact center with 200 seats can expect around 25-50 MB of hourly data transfer when all users are logged in.

[#integration-requirements]
== Integration requirements
Set up xref:acd-integration:how-integrations-work.adoc[integrations] to import and process contact data and agent status data from external systems, such as automatic call distributors (ACD) or customer relationship management (CRM) systems.
We support a wide range of cloud and on-premise integrations.

Install xref:acd-integration:install-cloud-link.adoc[Cloud Link] to regularly import data from on-premise and CSV integrations.

Data requests do not interfere with the main functions of communication software, such as telephony or email platforms.

Requests for real-time agent status information may use a direct socket feed. These feeds only transfer activity changes of agents (including a timestamp, an agent ID, and a status code) and are approximately 1kB each.