= Use Help Center
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:topic-type-concept:
:description: Learn how to find all the information you need to use Peopleware in Help Center.

Help Center is our self-service knowledge portal. It can help you work with Peopleware.
Here you can find answers to your configuration questions, learn all about the Peopleware features, and look up new terms in the glossary.

[#select-your-language]
== Select your language
Help Center is available in six languages. To select the language, use the drop-down menu at the top right.  
If you select an article from the navigation that is not available in your preferred language, you will be automatically redirected to the English version.

[#browse-through-the-sections]
== Browse through the sections
Use the tiles in the homepage to access the main sections with just one click.  
You can also use the navigation bar on the left side of each article to open the subsections and access other articles.

[#use-the-search-bar]
== Use the search bar
Enter keywords in the search bar at the top to find the articles you need. On the results page, use the WFM plan labels to filter the search results.

[#browse-the-glossary]
== Browse the glossary
The glossary includes terms and abbreviations that are used in Help Center articles, plus other industry-specific terms. You can access it from the top navigation bar on every Help Center article. Use the dropdown menu at the top right to see it in another language.

[#open-a-support-ticket]
== Open a support ticket
If a Help Center article does not answer your question, you can access the support page and open a ticket to get individual technical assistance. You need to log in to submit a ticket.

[#download-software-and-technical-manuals]
== Download software and technical manuals
From the homepage, you can also access the link:https://downloads.peopleware.com/en[downloads page], where you can find up-to-date installers, tools, and technical documentation that you might need when working with Peopleware.

[#read-the-terms-and-conditions]
== Read the terms and conditions
Scroll down in each page to access Peopleware's terms of use, terms and conditions, and privacy policy.

[#check-system-status]
== Check system status
Click the Status link in the footer to check the system status of Peopleware. You can also subscribe to email updates to be informed when incidents are reported or resolved.