= Give employees access to Me
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn what employees can do in Me. Create accounts to allow them to log in to Me.
:related-articles: configure-me.adoc, explore-me.adoc
:page-aliases: injixo-me-rollout

Me is our self-service portal. Give your employees access to Me if you want them to perform one or more of the following tasks:

- View their own schedule
- View their team members’ schedules
- Participate in shift bidding
- Swap shifts with other employees
- Request time off
- Change their availability for certain time periods

An employee can access Me via their Peopleware account. In this article, you will learn how to create accounts for your employees.

[#create-an-account-for-each-employee]
== Create an account for each employee
1. Go to _WFM > Administration > Scheduling > Employees_{:.breadcrumbs}
2. Click an **employee**. (If you haven't added employees yet, xref:administration:employee-overview.adoc[create an employee first].) A form containing all information about that employee will open to the right.
3. Scroll down to _Personal Data_ and enter an email address in the field **Peopleware Login (Email)**.
4. Click **OK**.
5. Click **Account** in the top menu and find the employee you just edited.
6. Click the **employee name**.
7. On the right, click **Set new password**. Type in a password that matches the requirements below the password field.
8. Write down the combination of email address and password where you will easily find it later. The email address and password are the employee's login credentials for their new Peopleware account. Click **Save**.
9. Inform the employee about their login credentials and that they can log in at https://app.peopleware.com/login.

[#allow-your-employees-to-set-their-passwords-themselves]
== Allow your employees to set their passwords themselves
You can allow your employees to create the password for their account themselves. To create their own password, the employee must have access to the email address that you configured for their login.

First, follow steps 1-4 as described above and inform each employee that you have created an account for them using that email address. Then, send your employees the following instructions:

1. Go to https://app.peopleware.com/login and click **Forgot your password?**.
2. Enter the email address that I sent you and click **Send instructions**. An email with a password reset link is sent to your email inbox.
3. Find the email, open it and click the **reset link**.
4. Choose a new password and enter it twice to confirm it. Click **Save new password**.
5. Go to https://app.peopleware.com/login and log in with your email address and your new password to access Me.