= Create and manage selections
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to create selections and add them to people to make it easier to group and filter people.
:related-articles: filter-with-selections.adoc

Selections group people for filtering purposes.
You can create selections following any grouping criteria. Selections work similarly to xref:people:advanced-filters.adoc[employee filters], with the following differences:

- With selections you can create your own grouping criteria.
- With employee filters the grouping criteria are based on existing configuration elements, e.g. planning units, skills, and contracts.

Employee filters are not available in Essential.
If you use Essential, you can use selections to group people according to configuration elements.

Selections are commonly used to group people with the following characteristics:

- Report to the same manager
- Work from home
- New hires who might need extra support or monitoring
- Can step in for other people on short notice
- Have additional responsibilities that are not relevant for scheduling, e.g. first helpers

[#create-selections]
== Create selections
1. In menu:Plan[Configuration>Selections], click btn:[Create] at the top right.
2. Enter the following information:
   - **Name**
   - **Abbreviation**
   - (Optional) **Description**
3. Click btn:[Save].

Now, you can add the following configuration data to your selection:

- xref:#subselections[Subselections]
- xref:administration:work-time-pattern-models.adoc[Work time pattern models]
- Time management rules

[#add-selections-to-people]
== Add selections to people
To add selections to people, you need to xref:administration:selections.adoc#create-selections[create a selection] first.

1. Go to menu:People[Overview].
2. Select a person from the list.
3. In the left-side menu, click **Planning**.
4. In the *Selections* section, click {icon-plus} **Add**.
5. Select the selections you want to add to the person.
6. (Optional) Select **Valid from** and **Valid to** dates if you want to add the selections only temporarily to the person.
7. Click btn:[Save].

[#remove-selections-from-people]
== Remove selections from people
1. Go to menu:People[].
2. Select a person from the list.
3. In the left-side menu, click **Planning**.
4. In the *Selections* section, hover over the selection that you want to remove and click the {icon-delete}.
5. In the confirmation window, click btn:[Remove].

[#manage-people-in-a-selection]
== Manage people in a selection
In menu:People[], you can filter people by the selections to which they belong.

To do so, click btn:[{icon-filter} Filter] and, in the **Selection** drop-down, select the selection by which you want to filter.

The list updates to show only people in that selection. To access a person's settings, click their row on the list.

[#subselections]
== Subselections
If you use Classic, Advanced WFM, or Enterprise WFM, you can add existing selections to another one, which we call subselections.
This is useful to filter employees from all the subselections at once by using the main or parent selection.

To establish a selection hierarchy, xref:administration:selections.adoc#create-selections[create the subselections] first.

Then, you can edit a selection to add subselections as follows:

1. Go to menu:Plan[Configuration>Selections].
2. Click the selection you want to use as a parent selection in the selections list.
3. In the **Subselections** section, click {icon-plus} **Add**.
4. Complete the following fields:
   - **Selections**: Select all selections you want to add as subselections.
   - (Optional) **Valid from/Valid to**: Configure these dates if you want to add the subselection only temporarily to the main selection.
5. Click btn:[Save].

To edit or remove a subselection, hover over it in the **Subselections** list in the configuration window and click the {icon-arrow-up-right-from-square} or the {icon-delete}.

[NOTE]
====
====
>
[NOTE]
====
You cannot see that a selection is a subselection or a main selection in the list. To check whether a selection includes subselections, click its row in the list in menu:Plan[Configuration>Selections].
If you often work with subselections, you can name them so that you can recognize their relationship to the main selection.
====
[#delete-a-selection]
== Delete a selection
1. Go to menu:Plan[Configuration>Selections].
2. In the list, hover over the selection you want to delete and click the {icon-delete} on the right.
3. In the confirmation window, click btn:[Delete].