= Set a validity period
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Use the validity period to limit the time period in which configuration elements are active.
:page-aliases: valid-from-to-dates

With validity periods, you can set a configuration for a limited amount of time. You can program configuration changes to automatically occur in the future without further manual input.

Validity periods are always optional. If you do not specify a validity period, the configuration will be effective immediately and will not change until you manually edit it.

Validity periods are available in menu:WFM[Administration>Scheduling].

[NOTE]
====
Day models
====
>
[NOTE]
====
Validity periods for day models may not be available in your tenant. If you want to use them, contact your Peopleware consultant.
====
[#use-validity-periods]
== Use validity periods
You can set a validity period when creating configuration data.

Example: You want one planning unit to temporarily take over the Calls activity to avoid overloading your other planning units. You can add the Calls activity to a second planning unit and define the validity period for this configuration:

1. Go to **Planning units**.
2. Select the planning unit to which you want to add the activity.
3. Go to the **Activities** section on the right.
4. Click the {icon-wfm-add}.
5. Enter a **Valid from** and **Valid to** date. This is the validity period.
6. Choose the activity and set **From** and **To** hours.
7. {btn-ok}

[#edit-a-validity-period]
== Edit a validity period
You can also edit the validity period for existing configuration data.

Example: You want to extend the contract for a certain person. You can edit the validity period of the person's contract:

1. Go to **Employees**.
2. Select the employee whose contract you want to extend.
3. Go to the **Contracts** section on the right.
4. Click the {icon-wfm-edit} next to the contract you want to extend.
5. Edit the **Valid to** field.
6. {btn-ok}