= Configure roles
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn which roles are available, change their permissions, create new roles, and assign roles to people.
:related-articles: predefined-user-roles.adoc, workload-permissions.adoc
:page-aliases: user-and-role-authorization

[#what-are-roles]
== About roles
A role groups people with the same set of permissions for the apps and features in Peopleware, e.g. _Forecast_{:.menu-item}, or to the features in WFM, e.g. _WFM > Administration_{:.breadcrumbs}.

Every role can be marked as a default role in the role settings.
Peopleware assigns roles with the **Default role** setting to every new user account.
All roles except the predefined **Everyone** role can be unassigned from any user account at any time.
For more information see xref:account:predefined-user-roles.adoc[Predefined roles].

[NOTE]
====
====
>
[NOTE]
====
In Essential WFM and Advanced WFM, you can configure xref:forecast:workload-permissions.adoc#configure-workload-permissions[permissions for all workloads]. In Enterprise WFM, you can additionally configure xref:forecast:workload-permissions.adoc#configure-individual-workload-permissions[permissions for individual workloads], xref:monitoring:manage-dashboards.adoc#configure-dashboard-permissions[dashboards] and xref:account:role-permissions.adoc[roles] in _Account > Roles_{:.breadcrumbs}.
====
[#managing-roles]
== Manage roles
=== Prerequisites

To manage and configure roles, your role needs the **Full access to Roles** permission.
To configure WFM permissions, your role also needs the **Enable access to WFM** permission.

[#create-a-new-role]
=== Create a new role from scratch
To create a new role and configure all its settings from scratch, proceed as follows:

1. Go to _Account > Roles_{:.breadcrumbs}.
2. Click _Create role_{:.doc-button}.
3. In the _Basic information_{:.label} section, configure the following fields:
   - **Name**
   - (Optional) **Description**
4. Edit the role _permissions_{:.css}. To grant _permissions_{:.css}, check the checkbox of the feature.
5. Click _Save_{:.doc-button}.

[#duplicate-a-role]
=== Duplicate an existing role
Duplicating an existing role transfers all its settings, including permission settings, to the new role.
To duplicate a role, proceed as follows:

1. Go to _Account > Roles_{:.breadcrumbs}.
2. Find the role in the **Roles** table.
3. In the role entry, click the {icon-context-menu} on the right to display the role entry menu.
4. Click {icon-overlapping-boxes} Duplicate to immediately create the new, duplicated role.
5. (Optional) Edit the role settings as needed.

[#assign-roles-to-people]
=== Assign roles to people
1. Go to _People_{:.breadcrumbs}.
2. Select a person from the list.
3. In the left-side menu, click **Access**.
4. In the _Roles and admin access_{:.label} section, click {icon-edit} **Edit**.
5. Check the relevant checkboxes in the list.
   To limit the displayed roles, use the search field.
6. Click _Save_{:.doc-button}.

[#edit-roles]
=== Edit roles
1. Go to _Account > Roles_{:.breadcrumbs}.
2. Find the role in the Roles table.
3. Make the changes to the role and click _Save_{:.doc-button}.

[#delete-roles]
=== Delete roles
1. Go to _Account > Roles_{:.breadcrumbs}.
2. Click the {icon-context-menu} next to the role you want to delete.
3. Click {icon-delete} Delete.
4. In the window that opens, click _Delete_{:.doc-button} to confirm.

[#set-wfm-permissions]
== Set WFM _permissions_{:.css}
1. Under _Account > Roles_{:.breadcrumbs}, select a role.
2. In the **WFM** section, click _Show in WFM_{:.label}.
   You will be redirected to _WFM > Administration > System > Role authorization_{:.breadcrumbs}.
3. In the **Navigator** section on the right, check or uncheck the checkboxes to add or remove _permissions_{:.css}.

[NOTE]
====
====
>
[NOTE]
====
Individual _permissions_{:.css} can overwrite role-based _permissions_{:.css} (also for _people_{:.css} with admin access).
====
>
[NOTE]
====
Use only role-based _permissions_{:.css} whenever possible. You can change _permissions_{:.css} for individual _people_{:.css} under _WFM > Administration > System > User Authorization_{:.breadcrumbs} but such changes will overwrite the role-based _permissions_{:.css}.
====
>
[NOTE]
====
To reset specific _permissions_{:.css}, you may need to temporarily remove admin access to activate the grayed-out checkboxes on the user authorization page. Click the Reset icon {icon-asterisk} to reset the role to the configuration set in _Account > Roles_{:.breadcrumbs}.
====
[#manage-team-access-restrict-access-to-configuration-data]
== Manage team access: Restrict access to configuration data
If your organization includes several teams and you want to restrict access to the teams' data, you can add more than one role to a person. The _permissions_{:.css} defined by different roles are combined. You can restrict access to elements such as _planning units_{:.css}, _day models_{:.css}, activities, or reports.

**Example**

If all your planners should have access to the _schedule_{:.css} but each planner should only be able to edit the data of their own _planning unit_{:.css}, you can assign two roles to each planner.

You can create a new role with no access to specific _planning units_{:.css}, or remove access to all _planning units_{:.css} from an existing role. To remove access to all _planning units_{:.css} from an existing role, proceed as follows:

1. Go to _Account > Roles_{:.breadcrumbs}.
2. Select the role.
3. In the **WFM** section, click _View in WFM_{:.label}.
4. On the right, scroll to the _Planning Units_{:.label} section (or use the quick link on top).
5. Click the {icon-wfm-delete} next to the [ALL] entry to delete access to all _planning units_{:.css}.
6. Click _OK_{:.doc-button}.

Add access to the specific _planning unit_{:.css} to other roles as follows:

1. Select the second role.
2. In the _Planning Units_{:.label} section, click the {icon-wfm-add}.
3. Select the planning unit(s) from the list. Press **CTRL** or **Shift** while clicking to select multiple _planning units_{:.css}.
4. Under _Access Authorization_{:.label}, check one or more checkboxes to set **Read**, **Edit**, and **Delete** rights.
5. Click _OK_{:.doc-button}.

To complete the configuration, go to _People_{:.breadcrumbs} and xref:#assign-roles-to-people[assign the roles to your people].

[#view-people-in-schedules-and-shift-center]
=== View people in Schedules and Shift Center
You cannot add permissions to view specific people to a role. If you have access to a planning unit but cannot see a person in Schedules and Shift Center, you need to add permissions for at least one selection to which the person belongs.