= Manage comments
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to add, edit, and delete comments in Schedules.
:related-articles: schedules-overview.adoc, schedules-edit.adoc

In menu:Plan[Schedules], you can use comments to add information to your schedules. You can add, edit, and delete comments.

New to Schedules? Learn xref:scheduling:schedules-overview.adoc[the basics] and how to xref:scheduling:schedules-edit.adoc[edit a schedule] first.

[#add-a-comment]
== Add a comment
You can add one comment to each level for each person per day.<br>
To allow people to see comments in Me, follow the steps in the xref:#allow-people-to-see-comments[dedicated section below].

1. In menu:Plan[Schedules], set the xref:scheduling:schedules-overview.adoc#filter-data[filters] and the xref:scheduling:schedules-overview.adoc#schedule-area[view options] for your schedule.
2. In a person's row, double-click an hour or day cell.
3. In the **Comment** section on the left, enter a comment with a maximum length of 250 characters.
4. At the bottom left, click btn:[Save].<br>

In the xref:scheduling:schedules-overview.adoc#schedule-area[schedule area], hover over a cell with a {icon-comment} to see the comment.<br>
In xref:scheduling:schedules-overview.adoc#single-day-view-with-hour-columns[single-day view], the {icon-comment} is only displayed in the hour cell with the first scheduled activity.

You can also see or xref:scheduling:add-and-delete-activities-day-models-availabilities-and-comments.adoc#add-comments[add comments in Shift Center].

[#edit-or-delete-a-comment]
== Edit or delete a comment
1. In menu:Plan[Schedules], set the xref:scheduling:schedules-overview.adoc#filter-data[filters] and the xref:scheduling:schedules-overview.adoc#schedule-area[view options] for your schedule.
2. In a person's row, double-click an hour or day cell marked with a {icon-comment}.
3. In the **Comment** section on the left, edit or delete the comment text.
4. At the bottom left, click btn:[Save].

[#allow-people-to-see-comments]
== Allow people to see comments
To allow people to see the comments you add to their schedules, proceed as follows:

1. Make sure that the day to which you want to add a comment is included within a scheduling period with the status Published or Shift bidding enabled.
2. xref:#add-a-comment[Add your comment] to an hour or day cell in the xref:scheduling:schedules-overview.adoc#level-column[Schedule level].

People can see your comments in menu:Me[My Calendar] by selecting the xref:me:explore-me.adoc#see-your-schedule-my-calendar[daily view] and clicking the {icon-comment} in the **7 Day Agenda** section on the left.

[#frequently-asked-questions]
== Frequently asked questions
[%header, cols="1a,1a,".rstrip(',')]
|===
|Question
|Answer
|Can I copy and paste existing comments into other cells?
|No, you cannot copy and paste existing comments.
|Can I add, edit, or delete comments for several people at once?
|No, you cannot add, edit, or delete comments for several people at once. Learn how to xref:scheduling:add-and-delete-activities-day-models-availabilities-and-comments.adoc#add-activities-day-models-availabilities-or-comments-to-multiple-people[add several identical comments in one day in Shift Center].
|===