= Batch replace an activity
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to replace an activity with another activity in an existing schedule.

The *Replace activities* functionality replaces all instances of an activity with another activity in an existing schedule.

[#prerequisites]
== Prerequisites
To use the *Replace activities* functionality, the following conditions need to apply:

- There is a schedule.
- Both the activity that you want to remove and the one with which you want to replace it are assigned to the same xref:administration:create-and-manage-planning-units.adoc[planning unit].

[#batch-replace-an-activity]
== Batch replace an activity
1. {nav-to-plan-schedules}
2. Select a date range from the date picker.
3. From the btn:[Scheduling actions] drop-down menu, select *Replace activities*.
4. In the page that opens, configure the replacing process. +
In the *Settings* section configure the following parameters:
   - *Planning unit*: After you select a planning unit, the list in the *Employees* section below updates and displays all the people assigned to the planning unit.
   - *Activity to be replaced*
   - *Replace activity with*: Select the activity that will replace the *Activity to be replaced*.
   - *Levels*: Check one or more checkboxes to select the xref:ROOT:glossary/overview/#level[levels]  in which the activity will be replaced.
   - *Date range*: By default, the date range is the one you selected in step 2. You can select a different date range. +
In the *Employees* section, select the people for whom you want to replace the activity. By default, Peopleware displays and pre-selects all the people assigned to the selected planning unit.
   - (Optional) Click the {icon-selection-filter-s} or the {icon-schedules-filter-employees-s} to filter out people. By default, all checkboxes are checked.
   - Uncheck the checkboxes next to the names of the people that you want to exclude. Uncheck the checkbox next to *Name* in the header to deselect all entries in the list.
5. At the bottom left, click btn:[Replace activities].

A process starts in the background. You are redirected to {bc-plan-schedules} and see a success or an error message at the top of the page. +
Go to xref:general:jobstatus.adoc[Job status] to track the progress of the process. If the process fails, click the related entry to see the job details and the cause of the failure.