= Exclude activities from optimized scheduling
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:topic-type-task:
:description: Prevent plannable activities from being scheduled with the Create optimized schedule feature.
:related-articles: schedules-optimized-schedules.adoc, work-with-attributes.adoc, concept-scheduling-rules.adoc

This article explains how to prevent individual, plannable activities from being scheduled with the *Create optimized schedule* feature.
For example, use this feature to make sure that a day model's base activity is not written to the actual schedule.

[NOTE]
====
Excluding an activity from scheduling can lead to schedules that no longer comply with applicable scheduling rules related to minimum work hours, minimum period between activities and others.
In such cases, Peopleware can only create an optimized schedule if the person that triggers the optimization job has the permissions required to violate these scheduling rules.
====
[#prerequisites]
== Prerequisites
[NOTE]
====
This is an add-on feature that needs to be licensed separately.
For more information, get in touch with your Peopleware representative.
====
[#permissions]
=== Permissions
Your role needs to have the following functional permissions:

- *Plan*
  - *Access to Plan Configuration*
- *People*
  - *Edit People*

Additionally, your role needs object permissions to edit the relevant objects:

- Activity
- Attribute

[#steps]
== Steps
=== Create attribute

1. Go to menu:Plan[Configuration>Attributes].
2. Check if the following attribute already exists:
   - *Name*: `Optimisation: remove on writing`
   - *Type*: Yes/No
   - *Available for*: Activities
3. If the attribute does not exist, create it:
   1. In the Attributes overview table, click btn:[Create].
   2. Set the parameters as described in step 2.
      Make sure that the attribute name matches exactly, including capitalization and spacing.
   3. {btn-save}

The attribute can now be assigned to activities.

[#assign-attribute-activity]
=== Assign attribute to activity
1. Go to {bc-plan-config-activities}.
2. Open the activity you want to exclude from scheduling.
3. Navigate to the *Attributes* section.
4. {btn-add}
   Configure the new attribute:
   - *Attribute*: `Optimisation: remove on writing`.
   - *Value*: Yes
   - *Priority*: 1
   - (Optional): Set a validity period for the attribute assignment.
     If you set a validity period, the activity will only be excluded from scheduling during that period.
5. {btn-save}

*Create optimized schedule* jobs will from now on exclude this activity from scheduling.
The jobs' logs contain information about which activities were removed from the schedule based on this attribute.