= Use levels
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to use levels to create backups of your schedule.
:page-aliases: best-practice-level-copy

Levels represent different versions of your schedule. With levels, you can compare various schedules and experiment with changes without altering the original schedule.

When you make changes to your schedule, you might overwrite or delete important information. By saving a copy of your schedule in a separate level, you can restore this information if needed.

Adjustments to the schedule can be necessary in the following situations:

- You accidentally overwrite a schedule containing approved time off for your employees. To avoid losing the original schedule, create a backup version in the Version 1 level.
- Call volumes or AHT differ from forecasted values. To test schedule changes without losing the original schedule, create a backup version in the Actual level.
- You make adjustments during the day due to deviations from the original schedule, for example in case of an increase in call volumes or people calling sick. To compare the adjusted schedule with the original one and identify impactful factors, copy the original schedule from the Schedule level to the Actual level.

[#copy-a-schedule-to-another-level]
== Copy a schedule to another level
1. Go to menu:Plan[Schedules] and select the date range of the schedule you want to copy.
2. From the btn:[Scheduling actions] menu, click **Copy level content**.
3. In the **Settings** section, configure the following fields:
   - **Planning unit**
   - **Source level**: The level from which you want to copy the scheduling data.
     If you copy from an empty level, the target level data will be deleted.
   - **Target level**: The level to which you want to copy the scheduling data.
   - **Date range**: This field is pre-filled with the time range selected in Schedules.
   - (Optional) **Target start date**: The date when the copied scheduling data should begin in the target level.
   - (Optional) **Empty source level content after copying**: Check this checkbox to delete the existing content from the source level.
4. (Optional) In the **Employees** section, check or uncheck the checkboxes next to the name of the people for whom you want to empty the level.<br>Use the {icon-schedules-filter-employees-u} and the {icon-filter-u} to filter people from the employees list with an employee filter or a selection from the drop-down menu.
5. Click btn:[Copy level content].

Go to xref:general:jobstatus.adoc[Job status] to view the progress of a level copy. When the level is copied, you see a link to the corresponding report.