= Understand day models
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn what day model types there are, what you need to consider before you can create a day model and what impact changing a day model has on the schedule.
:related-articles: daymodel-creation.adoc

Day models are templates for shifts. They represent the working day for the people you schedule and define the start and end times of shifts, as well as how many hours a person works per day and when they are available to work. Schedules are created based on your day models.

By default, day models you create are automatically assigned to all planning units in your organization. To change this default, xref:administration:create-and-manage-planning-units.adoc#limit-day-models[edit the planning unit]. During schedule optimization, only day models added to the planning unit are considered.

If the day models configured for your planning unit do not cover some working agreements, you can also add personal day models to individual people. During schedule optimization, only the personal day models are used for that person.

Day models contain presence, absence and break activities of a shift. This is why you need to xref:administration:daymodel-creation.adoc#add-activities-to-day-models[add relevant activities to day models].

Day models are added to xref:administration:shift-sequences.adoc[shift sequences] and can be grouped in xref:administration:work-time-pattern-models.adoc#create-week-time-patterns[week time patterns].

[#types-of-day-models]
== Types of day models
There are three different types of day models.

[NOTE]
====
- Day models of type Fixed are also called fixed day models. +
- Day models of type Variable are also called variable day models.
====
[%header, cols="1a,1a,".rstrip(',')]
|===
|Type
|Description
|Fixed
|Shifts with a fixed day model have a fixed start and end time that cannot be moved. There is always only one possible shift resulting from a fixed day model. Fixed day models are typically added to xref:administration:shift-sequences.adoc[shift sequences].
|Variable
|Shifts with a variable day model have a flexible start time within a defined time frame. This results in multiple possible shifts. Variable day models that are added to shift sequences will automatically become fixed day models because they are set to the first possible start position of a shift.
|Availability
|This day model type is used to define a time range that is shorter than the planning unit's business hours. After inserting shift sequences that contain this day model type, Peopleware selects day models that are compatible with this availability range during optimization and in shift bidding. You can also use this type to configure availabilities for several people at once.
|===

[#when-to-use-which-day-model-in-scheduling]
== When to use which day model in scheduling
There is no single use case for when to use which day model type, but the following list provides some general guidance:

- Fixed: Use fixed day models to schedule people with fixed working times. Their shifts will always start and end at a fixed time and cannot be moved within the schedule.
  You can use fixed day models in work time pattern models to xref:scheduling:scheduling-optimization.adoc[create optimized schedules], to define repeating weekly patterns in xref:scheduling:schedules-insert-shift-sequences.adoc[shift sequences], or if you use xref:scheduling:schedules-shift-bidding.adoc[shift bidding].
- Variable: Use variable day models to schedule people with flexible working hours. A person can be scheduled for different shifts using a single day model of this type. This day model is typically used when xref:scheduling:scheduling-optimization.adoc[creating optimized schedules] or in xref:scheduling:schedules-shift-bidding.adoc[shift bidding].
- Availability: If your planning unit's business hours span a larger time frame than one working day, you can limit the scheduling options. To limit the availability for several people at once, use day models of type Availability and add them to shift sequences. Alternatively, you can xref:administration:availabilities.adoc[configure availabilities for individual people] in the employee settings. Both are considered during schedule optimization if scheduling rule 2611 is activated.

As an alternative to availabilities, you can use xref:administration:shift-sequences.adoc[shift sequences] or week time patterns in xref:administration:work-time-pattern-models.adoc#create-week-time-patterns[work time pattern models]. You can also use both to rotate early and late shifts, for example.

We recommend creating a limited set of variable day models (combined with xref:administration:availabilities.adoc[availabilities of your people]) instead of creating a large number of fixed day models.

[#base-activity-and-shift-duration]
== Base activity and shift duration
For fixed and variable day models, you always need to set up a base activity for each day model to define the total shift duration. In both day model types, you can add more activities that overlay the base activity. The duration of the other activities must not exceed the duration of the base activity.

The base activity covers the total time a scheduled person is present during a shift including breaks and other unpaid activities. It is the first activity that you select when creating a new day model, and you cannot delete it or edit it after saving the day model.

The total time of a scheduled shift including breaks is the gross shift duration. After deducting unpaid activities, such as breaks or set-up times, the resulting working time is the net shift duration. You can see the net shift duration under the name Actual time in Schedules and in Shift Center. Note that contracts also specify net times.

The length of a day model must comply with the working hours in your xref:administration:create-contracts.adoc[contracts].
For example, a contract with 40 hours of weekly working time distributed over 5 days a week requires a day model with a net working time of 8 hours per day. A contract with 37.5 hours per week needs one with 7.5 hours.

Use the Present activity (ID 1) as base activity and make sure it is configured as Replaceable. Then, the Job optimization and Create optimized schedules functionalities can replace the Present activity with other activities, as long as they have xref:forecast:task-set-up-staff-requirement-calculation.adoc[calculated staff requirements] and are configured as Plannable.

[#fixed-elements-vs-corridors]
=== Fixed elements vs. corridors
You can create a corridor element if you add an activity with a duration shorter than the time between the element's start and end time. Corridor elements overlay all fixed elements in a shift. Optimized scheduling will move corridor elements around to optimize coverage. Corridors as such can overlap, but activities within two corridors cannot.

When you manually insert a day model into the schedule, corridor elements are placed at the earliest possible time of the corridor. You can manually move corridors within their defined intervals.

When the duration of a corridor element exactly matches the configured start and end time of the element, a fixed element is created instead.