= Configure day models
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to create day models of the types Fixed, Variable, and Availability, and how to add activities to day models.
:related-articles: daymodel-basics.adoc, set-a-validity-period.adoc
:page-aliases: day-models-overview

New to day models? Learn the xref:administration:daymodel-basics.adoc[basics] first.

[#create-day-models]
== Prerequisites
To create day models, you need to have a role with the following permissions:

- Full access to Configuration in Plan

To edit day models, you need to have a role with the following object permissions:

- Read, edit and delete for day models
- Read, edit and delete for activities contained in day models

[#create-day-models]
== Create day models
You can create and edit day models under menu:Plan[Configuration>Day models].

1. To create a new day model, click btn:[Create].
2. From the *Type* drop-down menu, select the day model type you want to configure.
3. Configure your day model. +
To find out more about the configuration options for each day model type, see the following sections.
4. To save the day model, click btn:[Save].

Now, you can xref:administration:create-and-manage-planning-units.adoc#limit-day-models[add activities ; features/administration/daymodels/daymodel-creation.md ; #add-activities-to-day-models %} to the new day model.

[NOTE]
====
If you work with a xref:best-practices:tips-on-shift-center-usage.adoc[limited number of day models in your planning unit], you may need to assign new day models to your planning unit. If you use work time pattern models, update the week time pattern(s).
====
[#fixed]
=== Fixed
[%header, cols="1a,1a,".rstrip(',')]
|===
|*Parameter*
|*Description*
|Name
|Unique name to describe the day model. We recommend specifying the day model type and its start and end times, e.g. 8-16:30-fix.
|Abbreviation
|This version of the name is displayed in reports and in Schedules. We recommend using the specified name or a shorter version of it.
|Shortcut
|Optional keyboard shortcut to help you insert the day model more quickly in Shift Center. Learn more about xref:ROOT:shortcuts[.
|Color
|The color that appears in the schedule and on configuration data pages. +It can help you quickly identify the length, day model type, or included activities.
|Valid from/Valid to
|Optional period during which the day model can be used. + It might not be available in your tenant. Learn more about xref:administration:set-a-validity-period.adoc[valid from/to dates].
|Start time
|Time at which the fixed shift begins.
|Total shift duration
|Duration of the shift in hours. +If you configure this value, it will replace the configured end time. +Note: Day models of type Fixed can span up to two days. To create a night shift, add up to 24 hours to the end time when creating the day model, or use the total shift duration. The maximum value is 48:00 (h).
|Activity
|The first activity is the xref:administration:daymodel-basics.adoc[base activity].
|===

[#change-the-base-activity]
=== Change the base activity
1. Select a day model.
2. In the *Assignments* section, click the *Base activity*.
3. {select-activity}
4. {btn-save}

[#variable]
=== Variable
[%header, cols="1a,1a,".rstrip(',')]
|===
|*Parameter*
|*Description*
|Name
|Unique name to describe the day model. We recommend specifying the day model type and its start and end times, e.g. var-8-20-8.
|Abbreviation
|This version of the name is displayed in reports and in Schedules. We recommend using the specified name or a shorter version of it.
|Color
|The color appears in the schedule and on configuration data pages +It can help you quickly identify the length, day model type, or included activities.
|Valid from/Valid to
|Optional period during which the day model can be used. +It might not be available in your tenant. Learn more about xref:administration:set-a-validity-period.adoc[valid from/to dates].
|Start time
|Earliest possible time at which the shift can start.
|Time frame duration
|Number of hours between the earliest start and latest end time of the shift. +This will replace the Time Frame End.
|Total shift duration
|Total shift duration including breaks. The duration must be shorter than the time frame. If the shift duration equals the time frame, the day model automatically becomes a day model of type Fixed.
|Interval
|Interval in which a shift can start within the defined time frame. For example, with an interval of 30, the shift can begin every 30 minutes within the defined time frame.
|Activity
|The first activity is the xref:administration:daymodel-basics.adoc[base activity]. +Note: You cannot change the base activity after saving the day model.
|===

[#availability]
=== Availability
Use this day model type e.g. in shift sequences to configure availabilities for several people at once.
Note that day model availabilities overwrite availabilities entered by people in Me as well as availabilities that have been manually added in Shift Center.
Learn more about xref:administration:availabilities.adoc[availabilities].

[%header, cols="1a,1a,".rstrip(',')]
|===
|*Parameter*
|*Description*
|Name
|Unique name to describe the day model. We recommend specifying the day model type and its start and end times, e.g. avail-8-16.
|Abbreviation
|This version of the name is displayed in reports and in Schedules. We recommend using the specified name or a shorter version of it.
|Color
|The color appears in the schedule and on configuration data pages +It can be helpful when setting up shift sequences, for example.
|Valid from/Valid to
|Optional period during which the day model can be used. + It might not be available in your tenant. Learn more about xref:administration:set-a-validity-period.adoc[valid from/to dates].
|Start time
|Earliest possible time at which the shift can start.
|Total shift duration
|Number of hours between the earliest start and latest end time of the shift. The maximum value is 48 hours.
|===

[#add-activities-to-day-models]
== Add activities to day models
To further define an existing day model, you can add breaks or other activities to it.
Configure other activities if you need to represent specific tasks people should work on at a given time in a shift.
These special activities can be, for example, checking the organization's social media channels or back-office tasks.

To add activities, you need to xref:administration:daymodel-creation.adoc#create-day-models[create the day model] first.

The schedule optimization can replace activities of type Presence that are configured as Replaceable.
If you do not want to schedule people to work on any special activities, the base activity is the only activity of type Presence in your day model.
Keep in mind that configuring activities in day models will limit the flexibility of optimization features (e.g. full optimization, extra activities, meetings).
To keep the optimization as flexible as possible and to avoid scheduling errors, we recommend keeping the configuration of activities of type Presence in day models to a minimum.

[NOTE]
====
The first activity you add to a day model is automatically the base activity. You cannot change or delete a base activity after saving the day model.
We recommend using the activity Present as base activity. Find out more about the xref:administration:daymodel-basics.adoc#base-activity-and-shift-duration[base activity].
====
[#add-a-presence-or-absence-activity]
=== Add a presence or absence activity
To add a presence or absence activity to an existing day model, proceed as follows:

1. Select a day model.
2. In the *Assignments* section, click the contextual menu {icon-context-menu} on the *Presences and absences* row.
3. Click *+ Add*.
4. Configure the activity:
   - Select an *Activity* from the drop-down menu.
   - *Start* and *End*: +
If the *Relative to Start of Shift* checkbox is checked: Define the number of hours/minutes after the start of the shift at which you want the activity to start and end (e.g. for 1.5 hours, enter 1:30). +
If the *Relative to Start of Shift* checkbox is unchecked: Define the exact time after the start of the shift at which you want the activity to start and end (e.g. for 2pm, enter 14:00).
   - *Total activity duration*: If you configure a duration that is longer than the time between the configured start and end times, you create a xref:administration:daymodel-basics.adoc#fixed-elements-vs-corridors[corridor] within which the activity can be moved.
   - *Interval*: We recommend using the same interval as your ACD. The activity length must be divisible by the selected interval. +
If you enter 0, the start time of the activity is fixed and the activity cannot be moved within a corridor.
   - *Relative to start of shift*: +
If checked (default), the activity starts at the defined number of hours/minutes after the shift start. If the shift is moved, the activity is moved as well. +
If unchecked, the activity starts at the exact configured time. When you move a variable shift, the activities will not move. This can be useful, e.g. when employees with different shifts need to attend a team meeting at the same time.

5. {btn-ok}

[#add-a-break-activity]
=== Add a break activity
To add a break activity for optimized scheduling and shift bidding to an existing variable and fixed day model, proceed as follows:

1. Select a day model.
2. In the *Assignments* section, click the contextual menu {icon-context-menu} on the *Breaks* row.
3. Click *+ Add*.
4. Configure the break:
   - Select a break *Activity* from the drop-down menu.
   - *Start* and *End*: +
If the *Relative to Start of Shift* checkbox is checked: Define the number of hours/minutes after the start of the shift at which you want the break to start and end (e.g. for 4.5 hours, enter 4:30). By default, breaks are entered relative to the start of the shift, because they usually start after a certain time at work. +
If the *Relative to Start of Shift* checkbox is unchecked: Define the exact time after the start of the shift at which you want the break to start and end (e.g. for 1pm, enter 13:00).
   - *Total activity duration*: If you configure a duration that is longer than the time between the configured start and end times, you create a xref:administration:daymodel-basics.adoc#fixed-elements-vs-corridors[corridor] within which the break can be moved.
   - *Interval*: Use the same interval as your ACD. The break length must be divisible by the selected interval. +
If you enter 0, the start time of the break is fixed and the break cannot be moved within a corridor.
   - *Relative to Start of Shift*: +
If checked (default), the break starts at the defined number of hours/minutes after the start of the shift. If the shift is moved, the break is moved as well. +
If unchecked, the break starts at the exact configured time. When you move a variable shift, the breaks will not move. This can be useful, e.g. if the cafeteria in your contact center is only open for a limited time.

5. Select a break option from the *Break* drop-down menu.
6. {btn-ok}

[#how-changes-to-day-models-affect-scheduling]
== How changes to day models affect scheduling
You can safely update properties that do not affect scheduling, such as the name, abbreviation, and color.
Before you create a new schedule, change the scheduling-related properties of a day model, such as start and end times, total shift duration, presences, absences, or breaks.
An internal copy of the original day model ensures that already scheduled shifts remain unchanged and visible.
In shift sequences and week time patterns, affected day models are automatically replaced.

Changes to the scheduling-related properties have the following effects:

- In Shift Center and Schedules, affected day models are underlined with a dotted line. Such day models can only be removed from the schedule.
- In shift bidding, any shift requirements values set for the original day model still apply, but any shifts generated and previously placed shift bids based on the day model are removed. People can no longer place new bids for such day models, and these shift bids are not included in a lottery or assignment before you generate shifts again.

[#add-day-models-to-people]
== Add day models to people
1. Go to {bc-people-overview}.
2. {select-person}
3. Under *Planning* in the left-side menu, click {icon-plus} *Add* in the *Day models* section.
4. Select the day models you want to add to the person.
5. (Optional) Select *Valid from* and *Valid to* dates if you want to add the day models only temporarily to the person.
6. {btn-save}

[#duplicate-day-models]
== Duplicate day models
Learn how to xref:general:duplicate-objects.adoc[duplicate day models].