= Manage your people's unavailabilities
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to use an activity of the Absence type to let your people define their unavailabilities.

Create a requestable activity of the Absence type to let your people define the times when they are unavailable to work.

Manage your people's unavailabilities with time-off requests to achieve the following:

- Define the periods during which people can add their unavailabilities.
- Set a deadline for unavailability requests, and approve or reject them.
- Keep track of your people's requests over time. Assess if their contracts align with their time-off needs.
- Allow people to set an unlimited number of unavailabilities.
- Allow people to set unavailibities for partial days.

This article provides an overview of the process. You can use it as a checklist.

[#1-create-the-activity-unavailable]
== 1. Create the activity Unavailable
1. In menu:Plan[Configuration] create a xref:administration:activities.adoc#create-an-activity[new activity].
2. Configure your activity as follows:
   - **Name**: Enter Unavailable. An abbreviation is generated automatically.
   - **Type**: Select **Absence**.
   - Check the **Requestable in Me** checkbox.
   - (Optional) Check the **Allow as full-day activity** checkbox.
3. Click btn:[Create activity].

[#2-create-a-time-off-period]
== 2. Create a time-off period
1. In {bc-plan-time-off}, create a xref:scheduling:time-off-periods-legacy.adoc#create-a-time-off-period[time-off period].
2. Enter the general information for your time-off period:
   - *Planning unit*.
   - (Optional) *Selection*.
   - **Activity**: Select **Unavailable**.
   - (Optional): **Deadline**.
   - **Status**: Select **Published**.
3. Click btn:[Create time-off period].

[#3-people-submit-their-requests]
== 3. People submit their requests
In {bc-me-time-off}, people can xref:me:explore-me.adoc#request-time-off[submit requests] for the activity Unavailable.

[#4-approve-or-reject-requests]
== 4. Approve or reject requests
In {bc-plan-time-off}, xref:scheduling:vacation-absences-management.adoc[approve or reject time-off requests] for the activity Unavailable.<br>
After you approve a person's request, the Schedule window in Shift Center shows a red cell with the abbreviation of the Unavailability activity for the time slot of the approved request. If you use **Create optimized schedules** or **Job optimization**, the person is not scheduled during the blocked time slot.

[#keep-track-of-the-requests]
== Keep track of the requests
In {bc-plan-shift-center}, you can see the details of approved time-off requests for the activity Unavailable.

1. Click the **Activities - Requirements** tab under the table. At the top, select a date range from the date picker and click btn:[Apply].
2. Expand the relevant planning unit in the top table.
3. Double-click a red cell labelled as Unavailable.
4. Click the **History** tab.
   You will see the details of the time-off request's approval:
   - Date/Time: Date and time of the approval.
   - Action: The action performed. In this case, Approve request.
   - User: The person who approved the request.
5. {btn-ok}

Go to {bc-plan-time-off} to xref:scheduling:vacation-absences-management.adoc#view-requests[see approved, pending and rejected requests].