= Untitled
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:topic-type-concept:

...and spending days fixing the schedule.

[#did-you-know]
==== Did you know...?
You don’t need to spend days fixing optimisation errors by manually adjusting schedules to correct problems or missing shifts. If you spend an hour a week doing this, thats up to 52 hours per year you spend copying and pasting or moving schedules manually. Just by checking a few things you might be able to find and fix the source of the problem in a few minutes.

[#what-you-should-do-is]
==== What you should do is...?
**Check for pre-scheduled Activities** - Take a look in _Shift Center_{:.menu-item} or in _Schedule_{:.menu-item} to see if activities are already written into the schedule. This will prevent other shifts or activities from being written.

**Check the Employees Contract settings** - Can the work time guidelines per day and week in the contract be met using the existing day models?

**Check the Employees settings** - If you still haven’t identified the issue, you will need to check the configuration for each individual employee who had an error.

**Check the Scheduling Rules** - Another source of error are the scheduling rules. If you or another user recently made changes, revert to your previous settings. If you are not sure if a change was made, try to manually insert a suitable day model for an employee in the _Shift Center_{:.menu-item}.

**Tip:**
_Check the scheduling report to identify the cause of errors_ - This report documents the scheduling process and lists any errors. If employees have been completely excluded from schedule generation, they will be listed on the first page. On the next pages, the report lists all employees for whom the schedule creation encountered errors. Check out our article about xref:best-practices:resolve-optimization-issues.adoc[common error messages]
