= Untitled
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:topic-type-concept:

...rather than using Work Time Pattern Models.

[#did-you-know]
==== Did you know...?
To force the optimization to use only some of the available day models you don't need to create personal Day Models for each employee. The optimizer uses all the day models that are assigned to the *Planning Unit*. It assigns day models to employees when the skills suit the included Activities. It also replaces Activities when the 'replaceable' checkbox is checked.

[#what-you-should-do-is]
==== What you should do is...?
An easier way to assign these day models to a group of employees is to assign a _Work Time Pattern Model_ to them. Think about how your day models should be organized for groups of employees. Work Time Pattern models can be organized by start time, by duration or the types of activities defined in those Day Models.
Each of these groups of Day Models is a _Week Time Pattern_, so create one per pattern. Assign each set to a _Work Time Pattern Model_ and this finally to your employees.

*Tip:* You can create a 3 week rotation such as 'Early, Mid, Late' using Week & Work Time Patterns. Remember to choose the right _Rotation_ Type in the Work Time Pattern Model.
