= Priority value for activities
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to protect activities from being overwritten by other activities.
:related-articles: activity-types-and-properties.adoc, importance-for-activities.adoc

You can define a priority value for each activity in menu:Plan[Configuration>Activities].
The priority value defines which activities can be overwritten by other activities during manual schedule updates or job optimization.

[#why-do-i-need-the-priority-value-for-activities]
== Why do I need the priority value for activities?
By default, all activities have the same priority. As a consequence, certain activities might be replaced by others if they have different staff requirements. You can ensure that certain activities are never overwritten by using the priority value (default: 1).

An activity with a high priority value (highest value: 1) cannot be replaced by activities that have a lower priority value. You can use this functionality if you want to ensure that an activity is never replaced by another.

[#prerequisites]
== Prerequisites
For prioritizing activities with the priority value, the following must be true:

- The activities that need to be prioritized are configured as xref:administration:activity-types-and-properties.adoc#activity-properties[Replaceable].
- If they are of type Present, the activities must have staff requirements.
- Scheduling rule *2660* _Check activity priority_ is activated.

== Example 1: Activity type Presence <a name="example-1-activity-type-presence-"></a> <!-- find a better title -->

- There are two activities: B2B hotline and B2C hotline.
- Both activities are of the type xref:administration:activity-types-and-properties.adoc#activity-types[Presence].
- B2B hotline is critical and should never be replaced by B2C hotline.

After creating an initial schedule, you recalculate your staff requirements according to current events for both activities to check if your activities are still properly staffed. If the staff requirements for B2C hotline have increased, run a job optimization to ensure that the activities are correctly balanced. However, by doing this, the job optimization might reassign people from B2B hotline to B2C hotline in the schedule.

To ensure that B2B hotline is never replaced by B2C hotline, assign a priority value of 1 to B2B hotline and a lower priority value (a number larger than 1) to B2C hotline.

If there aren't enough people to handle both activities simultaneously, the B2B hotline is always staffed before B2C hotline.

[#example-2-illness-and-home-office]
== Example 2: Illness and Home office
- There are two activities: Illness and Home office.
- Both activities are of type xref:administration:activity-types-and-properties.adoc#activity-types[Absence].

Because both activities are of type Absence, they do not have staff requirements. If you insert shift sequences that include Home office without defining a priority, Illness might be overwritten by Home office. This could cause problems for people who are ill that day and who are scheduled for Home office.

To prevent that Illness is replaced with Home office, assign a priority value of 1 to Illness and a priority value of 2 (or higher) to Home office. This will ensure that the Illness activity cannot be overwritten by the Home office activity.