= Configure accounting rules
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to configure accounting rules to refine your valuation strategy.

include::help-center:ROOT:partial$reusables/time-off-new.adoc[]

Accounting rules determine how time-off requests are evaluated. For time-off types with an entitlement (e.g., Vacation), they calculate how many days or hours are deducted if a request is approved. For other time-off types without entitlement (e.g., Sickness), accounting rules calculate how many hours or days count as "taken" if a request is approved. This is influenced by the following:

- Your [**valuation strategy**](https://help.peopleware.com/understand-valuation#valuation-strategies).
- Adjustments for holidays, weekends, or specific days.
- Rounding xref:#rounding[thresholds] for partial-day requests.

Learn more about [time-off valuation](https://help.peopleware.com/understand-valuation).

[#create-accounting-rules]
== Create accounting rules
To create an accounting rule, proceed as follows:

1. Go to **Time Off > Accounting rules**.
2. Click _Create_{:.doc-button} in the top-right corner.
3. Configure the following elements:
   - **Name**
   - [**Valuation strategy**](https://help.peopleware.com/understand-valuation#valuation-strategies)
   - Optional settings:
     - [**Consider bank holidays**](https://help.peopleware.com/understand-valuation#how-are-public-holidays-considered)
     - [**Ignore weekends**](https://help.peopleware.com/understand-valuation#how-are-weekends-considered)
     - [**Enable rounding**](https://help.peopleware.com/understand-valuation#rounding-). If you checked this checkbox, you can configure a xref:#rounding[**threshold type**].
   - xref:#contracts-in-accounting-rules[**Contracts**]: Limit the rule to specific contracts only.
4. Click **Create**.

[#rounding]
== Rounding
Check the checkbox Enable rounding in a rule, to configure thresholds and determine when a time-off request is rounded to a full or half day.

[#relative-threshold]
=== Relative threshold
Determine the percentage of a contractual or scheduled day from which time off is counted as a full day in the person’s entitlement.

Example: A person’s contract defines 8 working hours per working day. If you enter a threshold of 50%, any time off valuated with more than 4 hours is counted as a full day. Any time off valuated with less than or equal to 4 hours is counted as a half-day absence.

[#absolute-threshold]
=== Absolute threshold
Determine the amount of hours and minutes in a contractual or scheduled day from which the requested time off for a specific day is counted as a full day.

Example: A person’s contract defines 8 working hours per working day. If you enter a threshold of 4 hours, any time-off request valuated with 4 hours or more is counted as a full-day absence. Any time off valuated with less than 4 hours is counted as a half day.

[#contracts-in-accounting-rules]
== Contracts in Accounting rules
Since different contracts may require different accounting rules, you can assign a contract to specific accounting rules, so that the accounting rule only applies to people with these contracts. If you do not assign any contracts to an accounting rule, the accounting rule applies to all people in your tenant.

You can have only one accounting rule without any contract assigned but as many accounting rules with at least one contract as you wish. If a person requests a day off but has no contract assigned, the general accounting rule is used by default to determine the amount of hours or days to be deducted.

To add a contract to an accounting rule, proceed as follows:

1. In _Time Off > Accounting rules_{:.breadcrumbs}, select an accounting rule
2. In the **Contracts** section, click **{icon-edit} Edit**.
3. Check the checkboxes for all contracts you want to add. Use the search field if necessary.
4. Click _Save_{:.doc-button}.

[#adjusted-days]
== Adjusted days
Adjusted days let you define days on which only a certain amount of hours is deducted, even if a person requests an entire day off.

Example: In your organization, Easter Monday is considered a half-day working day. If a person requests the entire day off, only half a day should be deducted from their entitlement. To configure the accounting rule accordingly, add Easter Monday as an adjusted day in the accounting rule, select the deduction type **Relative to working times**, and enter a max. deduction of 50%.

To add adjusted days to an accounting rule, xref:#create-accounting-rules[create an accounting rule] first and proceed as follows:

1. In _Time Off > Accounting rules_{:.breadcrumbs}, select an accounting rule.
2. In the **Adjusted days** section, click **{icon-plus} Add**.
3. Select a **Day type**, e.g. Christmas Eve. Only day types with xref:administration:day-types.adoc#holiday-mode[holiday mode] activated are supported.
4. Select a **Deduction type**:
   - **Absolute**: Select this to define the amount of hours and minutes to be deducted if the full day is requested.
   - **Relative to working times**: Select this to define the percentage of hours and minutes to be deducted if the full day is requested.
5. **Max. deduction**: Enter the amount or percentage of hours and minutes to be deducted.
6. Click _Create_{:.doc-button}.