= Configure role permissions
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: Andreas Böttcher
:email: andreas.boettcher@peopleware.com
:topic-type-task:
:page-aliases: configure-user-roles.adoc
:product_label: advanced, enterprise

In {bc-account-roles}, you can restrict view and edit permissions for certain roles.
For example, if you want people with the Planner role to be able to assign the Standard Agent role only, you can edit the role permissions for the Planner role.

[NOTE]
====
People need a role with the permission {permissions-people-edit-people} to be able to assign any roles.
People can only assign the roles for which their role has view permissions.
====

[#allow-a-role-to-assign-specific-roles-only]
== Allow a role to assign specific roles only

To allow a role to assign one or more specific roles, proceed as follows:

1. Select the role whose permissions you want to edit.
2. In the *Account* section, click *Configure role permissions*.
3. In the *View* column, check the checkboxes next to the roles that the selected role should be able to assign.
4. Click {btn-save}.

The role you edited can only view and assign the roles you have selected in the role permissions.
If the role does not have the permission {permissions-account-full-access-to-roles}, it cannot edit roles.

[#allow-a-role-to-assign-and-edit-all-roles]
== Allow a role to assign and edit all roles

To allow a role to assign and edit all roles, proceed as follows:

1. Select the role you want to allow to assign and edit all roles.
2. In the *Account* section, check the checkbox {permissions-account-full-access-to-roles}.
3. Click {btn-save}.

The role you edited can view, assign and edit all roles.