= Configure user roles
:author: Andreas Böttcher
:email: andreas.boettcher@peopleware.com
:topic-type-task:
:page-aliases: user-and-role-authorzation.adoc
:product_label: advanced, enterprise

[#about-roles]
== About roles

A role groups people with the same set of permissions for the apps and features in Peopleware, e.g {bc-forecast-workloads} or to the features in WFM, e.g. {bc-wfm-administration}.

Every role can be marked as a default role in the role settings.
Peopleware assigns roles with the *Default role* setting to every new user account.
All roles except the predefined *Everyone* role can be unassigned from any user account at any time.

For more information see xref:predefined-user-roles.adoc[].

[NOTE]
====
In Essential WFM and Advanced WFM, you can configure workload permissions.
In Enterprise WFM, you can additionally configure permissions for individual workloads, dashboards and roles.
For more information, see:

* xref:forecast:workload-permissions.adoc[].
* xref:monitoring:dashboards/manage-dashboards.adoc[]
* xref:role-permissions.adoc[]
====

[#manage-roles]
== Manage roles

[#prerequisites]
=== Prerequisites

To manage and configure roles, your role needs the following permissions:

* {permission-roles-full-access-to-roles}

To configure WFM permissions, your role also needs the following permissions:

* {permission-wfm-enable-access-to-wfm}

[#create-role-from-scratch]
=== Create a new role from scratch

To create a new role and configure all its settings from scratch, proceed as follows:

. Go to {bc-account-roles}.
. Click btn:[Create role].
. In the *Basic information* section, configure the following fields:
* *Name*
* Optional: *Description*
. Edit the role permissions.
To grant permissions, check the checkbox of the feature.
. Click btn:[Save].

=== Duplicate an existing role <a name="duplicate-a-role"></a>

Duplicating an existing role transfers all its settings, including permission settings, to the new role.
To duplicate a role, proceed as follows:

1. Go to {bc-account-roles}.
2. Find the role in the *Roles* table.
3. In the role entry, click the image:help-center:ROOT:icons/3_dots_vertical.svg[] icon on the right to display the role entry menu.
4. Click {% icon overlapping_boxes | icon-only %} Duplicate to immediately create the new, duplicated role.
5. (Optional) Edit the role settings as needed.

=== Assign roles to people <a name="assign-roles-to-people"></a>

1. Go to _People_{:.breadcrumbs}.
2. Select a person from the list.
3. In the left-side menu, click **Access**.
4. In the _Roles and admin access_{:.label} section, click {% icon pencil | icon-only %} **Edit**.
5. Check the relevant checkboxes in the list.
To limit the displayed roles, use the search field.
6. Click _Save_{:.doc-button}.

=== Edit roles <a name="edit-roles"></a>

1. Go to _Account > Roles_{:.breadcrumbs}.
2. Find the role in the Roles table.
3. Make the changes to the role and click _Save_{:.doc-button}.

=== Delete roles <a name="delete-roles"></a>

1. Go to _Account > Roles_{:.breadcrumbs}.
2. Click the {% icon ellipsis_v %} next to the role you want to delete.
3. Click {% icon trash | icon-only %} Delete.
4. In the window that opens, click _Delete_{:.doc-button} to confirm.

== {see-also-title}

=== {see-also-concept}

* xref:predefined-user-roles.adoc[]
* xref:forecast:workload-permissions.adoc[]