= Five9
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Connect your Five9 ACD and prepare a custom report to use queue grouping by skills.
:related-articles: how-integrations-work.adoc, add-an-integration.adoc

A Five9 integration is a cloud integration that imports calls, agent status data, and real-time adherence data.

New to integrations? Learn xref:acd-integration:how-integrations-work.adoc[the basics] first.

[#prerequisites]
== Prerequisites
If you are grouping your queues by campaign, the integration reads the standard call log report from Five9.

If you are grouping your queues by skill, the integration needs a custom call log report from Five9 that includes skills in a new shared report folder in Five9. To import data from queues grouped by skills, follow the steps below in Five9:

[NOTE]
====
====
>
[NOTE]
====
Five9 distinguishes between lowercase and uppercase in folder and report names. Use the exact case for folder and report names as mentioned in the following steps.
====
1. Create a new shared report folder named **Shared Reports (injixo)**.
2. Customize the standard call log report by including the **SKILL** column.
3. Save the customized report as **Call Log with Skills** in the new shared folder.

For more detailed information on how to customize reports, refer to the Five9 Help Center.

[#add-a-five9-integration]
== Add a Five9 integration
1. Go to *Account > Integrations*{:.breadcrumbs}.
2. Click _Create_{:.doc-button}.
3. Enter a unique name for the new integration that identifies the data source.
4. From the **External system** drop-down menu, select **Five9**.
5. Click _Save_{:.doc-button}.

[#set-up-your-adp-integration]
== Set up your Five9 integration
1. In the **Credentials** section, enter the username and password for a Five9 user.<br>The user should have the following roles:
   - **Administrator**: Permissions can be limited to an empty set
   - **Supervisor**: The "Execute Web API requests" option must be enabled
   - **Reporting**.
2. In the **Configuration** section, enter the following information:
   - **Account region**: Select the region of your Five9 account.
   - **Group queues by**: Select how you want to group your queues. Note that skill-based grouping requires setting up a custom report in your Five9 account.
3. Click _Save_{:.doc-button}.

The integration starts importing data. The initial import can take up to 15 minutes. All queues from the connected system will automatically be available for mapping on the xref:forecast:create-workloads.adoc#create-workloads[workload configuration screen] in **Forecast**.

[#what-happens-in-the-event-of-parallel-agent-states]
== What happens in the event of parallel agent states?
Sometimes, Five9 reports multiple states for an agent for the same period, for example:

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|State
|Start time
|End time
|Ready
|13:00:00
|13:00:05
|Inbound
|13:00:00
|13:03:00
|===

To avoid one state overwriting the other, the integration changes the beginning of the longer state. The beginning of the longer state becomes the end of the shorter one:

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|State
|Start time
|End time
|Ready
|13:00:00
|13:00:05
|Inbound
|13:00:05
|13:03:00
|===