= ADP
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to connect your ADP system to import data about people, entitlements, and time tracking.
:related-articles: how-integrations-work.adoc

The ADP integration is a paid feature. If your organization is interested in this feature, get in touch with your consultant.

An ADP integration is a CSV-based integration that imports data about people, entitlements, and time tracking. Unlike other CSV-based integrations, you do not need to install Cloud Link to run it.

include::help-center:acd-integration:partial$integration-intro.adoc[]

== Prerequisites

- ADP provided you with the SFTP host and the credentials to access their online SFTP server.
- In ADP, you set up the xref:#generation-and-structure[file naming] and generation frequency for xref:#entitlements-data[entitlements], xref:#time-tracking-data[time tracking], and xref:#people-data[people] data.

[#add-an-adp-integration]
== Add an ADP integration
1. Go to {bc-account-integrations}.
2. {btn-create}
3. include::ROOT:partial$ui-interactions/enter-integration-name.adoc[]
4. From the **External system** drop-down menu, select **ADP**.
5. {btn-save}

[#set-up-your-adp-integration]
== Set up your ADP integration
1. In the **SFTP server credentials** section, enter the required information. See xref:#sftp-server-credentials[SFTP server credentials].
2. In the **Regional settings** section, select a **Time zone**. See the xref:#regional-settings[time zone requirements].
3. Click btn:[Save integration] to create the integration.
   The integration starts importing data within the first 15 minutes. See how Peopleware handles imported xref:#entitlements-data[entitlements], xref:#time-tracking-data[time tracking], and xref:#people-data[people] data.

[#settings-and-parameters]
== Settings and parameters
[#regional-settings]
=== Regional settings
Regional settings help ensure that Peopleware interprets imported data correctly.

[%header, cols="1a,1a,".rstrip(',')]
|===
|Field
|Description
|Time zone
|Determines how timestamps in imported files are interpreted. To ensure correct mapping, set the time zone to match ADP's system time zone. For example, use 'America/New_York' for U.S. Eastern Time, which automatically adjusts for daylight saving time.
|===

[#sftp-server-credentials]
=== SFTP server credentials
<style>
table {
   margin-left: 0px;
}
</style>

ADP should provide you with the necessary SFTP server credentials.

[%header, cols="1a,1a,".rstrip(',')]
|===
|Field
|Description
|Host
|The host provided by ADP
|Username
|The username provided by ADP
|Password
|The password provided by ADP
|Folder
|The folder on the SFTP server containing the import files
|===

[#import-files]
== Import files
[#generation-and-structure]
=== Generation and structure
ADP generates import files and hosts them on an online SFTP server.<br>
You can schedule the generation of import files to run at any desired interval. Get in touch with your ADP consultant.<br>
Each import file generated by ADP includes a timestamp in its filename that uses the format MMDDYYHHmmss (e.g., 031925122926 for a file generated on March 19, 2025 at 12:29:26 PM).<br>
All generated files should follow the naming convention outlined below:

<style>
table {
   margin-left: 0px;
}
</style>

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|Data type
|data type for file name
|Example file name
|Entitlements
|entitlements
|Peopleware_entitlements\_\_031925122926
|Time-tracking
|punches
|Peopleware_punches\_\_031925122926
|People
|roster
|Peopleware_roster\_\_031925122926
|===

Import files contain the full dataset for the day on which they are generated.

[#import-frequency]
=== Import frequency
The integration checks the SFTP server for files to be imported every 15 minutes. If there is a new file, the integration imports it. The import process is read-only: files are not modified after the import. Once a file has been downloaded, ADP may delete it from the SFTP server, depending on your SFTP server configuration.

[#entitlements-data]
== Entitlements data
[NOTE]
====
Entitlement imports require the new Time Off app. To learn more, contact your Peopleware consultant.
====
The integration imports time-off entitlements from ADP into account in Time Off.<br>
We recommend you set up daily entitlement exports, ideally before the business day starts.<br>
The data is imported as a CSV file named 'Peopleware_entitlements' followed by a timestamp for the export date time that uses the format MMDDYYHHmmss (e.g., Peopleware_entitlements\_\_031925122926).

The balance values in the entitlements file are defined in industrial time (e.g., 10.66 represents 10h 40min).

[#absence-types]
=== Absence types
The integration maps balances based on the time-off type in Peopleware (e.g. Vacation and Personal/Sick).<br>
If there is no match in Peopleware for a column name in the CSV file, the balance for that type is not updated in Peopleware.

See how the fields in the CSV file map to Peopleware fields:

<style>
table {
   margin-left: 0px;
}
</style>

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|ADP field
|Peopleware field
|Description
|Associate ID
|Personnel number
|Used as unique employee identifier
|Legal First Name
|n/A
|Ignored during the import
|Legal Last Name
|n/A
|Ignored during the import
|Vacation Balance
|Vacation entitlement / Vacation Current balance
|See xref:#how-peopleware-handles-imported-entitlements-data[how Peopleware handles imported entitlements data].
|Personal/Sick Balance
|Personal/Sick entitlement / Vacation Current balance
|See xref:#how-peopleware-handles-imported-entitlements-data[how Peopleware handles imported entitlements data].
|n/A
|Booking Date
|By default, Peopleware uses the date from the filename
|n/A
|Reason
|'Imported via [integration name]'
|===

[#how-peopleware-handles-imported-entitlements-data]
=== How Peopleware handles imported entitlements data
Peopleware handles the balance information from ADP as remaining entitlement.<br>
IF the ADP balance is the same as the Peopleware balance, the Peopleware time accounts do not change.<br>
If the ADP balance is different than the Peopleware balance, the Peopleware entitlement is adjusted so that the current balance matches the value in the CSV file.<br>
If the ADP balance is an empty value, the Peopleware entitlement does not change.<br>
See the following table:

[%header, cols="1a,1a,1a,1a,".rstrip(',')]
|===
|ADP balance
|Peopleware current balance
|Resulting Peopleware Entitlement value
|Resulting Peopleware Taken value
|300h
|300h
|No changes
|No changes
|310h
|300h
|+10h
|No changes
|290h
|300h
|-10h
|No changes
|No value
|300h
|No changes
|No changes
|===

[#time-tracking-data]
== Time Tracking data
[NOTE]
====
Time Tracking and punches imports require the Time Tracking app. To learn more about Time Tracking, contact your Peopleware consultant.
====
The integration imports punches from ADP into Peopleware as time-tracking data. The imported data appears in Intraday Adherence and Shift Center, and is used as the default source for adherence monitoring.<br>
The integration imports time tracking data every 15 minutes. Make sure that ADP exports time tracking data every 15 minutes.<br>
The data is imported as a CSV file named 'Peopleware_punches' followed by the timestamp of the export in the format MMDDYYHHmmss (e.g., Peopleware_punches\_\_031925122926).

The imported CSV file does not include any activity type. The ADP integration uses the activity **Present** with ID 1 for the time logs.

See how the fields in the CSV file map to Peopleware fields:

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|ADP field
|Peopleware field
|Description
|Associate ID
|Personnel number
|Used as unique employee identifier
|Legal First Name
|n/A
|Legal Last Name
|n/A
|Time In
|Start datetime
|Format `MM/DD/ HH:mm AM/PM` + Peopleware ignores rows with empty values.
|Time Out
|End datetime
|Format `MM/DD/ HH:mm AM/PM`  + Peopleware ignores rows with empty values.
|-
|Activity id
|The WFM **Present** activity with ID 1 is used
|===

[#people-data]
== People data
The integration imports people data every 15 minutes. We recommend you configure ADP exports accordingly.
The data is imported as a CSV file named "Peopleware_roster" followed by the timestamp of the export in the format MMDDYYHHmmss (e.g., Peopleware_roster\_\_031925122926).

See how the fields in the CSV file map to Peopleware fields:

[%header, cols="1a,1a,1a,".rstrip(',')]
|===
|ADP field
|Peopleware field
|Description
|Associate ID
|Personnel number
|Used as unique employee identifier
|Legal First Name
|First name
|
|Legal Last Name
|Last name
|
|-
|Email (Peopleware login)
|Peopleware uses a xref:#how-peopleware-handles-imported-people-data[placeholder email address] as default.
|Hire Date
|Staff membership (**From** date)
|
|Termination Date
|Staff membership (**To** date)
|
|Leave of Absence Start Date
|Staff membership
|See xref:#how-peopleware-handles-imported-people-data[how Peopleware handles leave of absence dates]
|Leave of Absence Expected Return Date
|Staff membership
|See xref:#how-peopleware-handles-imported-people-data[how Peopleware handles leave of absence dates]
|Job Title Description
|n/A
|Peopleware ignores this field
|Position Status
|-
|See xref:#how-peopleware-handles-imported-people-data[how Peopleware handles the position status]
|===

[#how-peopleware-handles-imported-people-data]
=== How Peopleware handles imported people data
Peopleware handles imported people data as follows:

If the ADP Associate ID does not match any existing personnel number, Peopleware creates a new person with the role/s set as **Default role** in {bc-account-roles}.<br>
If the ADP Associate ID matches an existing personnel number, Peopleware overwrites the existing information with the imported data.

Peopleware creates a placeholder email addresses for the people imported from ADP.<br> The email address is constructed as follows:
personnel_number_integration_configuration.id@noemail.invalid.

<style>
table {
   margin-left: 0px;
}
</style>

[%header, cols="1a,1a,".rstrip(',')]
|===
|Email address component
|Description
|personnel_number
|Corresponds to the ADP Associate ID
|integration_configuration_id
|Peopleware internal value
|@noemail.invalid
|Standard domain used in Peopleware for placeholder email addresses
|===

In ADP, you can define a membership with a position status. See how Peopleware handles the position status:

[%header, cols="1a,1a,".rstrip(',')]
|===
|ADP position status
|Effect on Peopleware Staff membership
|Active
|No changes
|Terminated +Deceased +Retired
|The employment period ends on the day of the file import, unless another `Termination Date` is specified for the person. +If the CSV file includes employees whose status is already 'Terminated', Peopleware creates new people that are shown as **Inactive**.
|Leave
|The staff membership ends on the `Leave of Absence Start Date`. A new staff membership starts on the `Leave of Absence Expected Return Date`. + If a person has the 'Leave' status after the `Leave of Absence Expected Return Date`, no new staff membership is created.
|===