= Sikom
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to connect your Sikom CRM to import data.
:related-articles: how-integrations-work.adoc, install-cloud-link.adoc, import-agent-status-data.adoc

A Sikom integration is an on-premise integration that imports call history, agent status and real-time adherence data.

The integration uses xref:acd-integration:install-cloud-link.adoc[Cloud Link].

include::help-center:acd-integration:partial$integration-intro.adoc[]

[#add-a-sikom-integration]
== Add a Sikom integration
1. Go to {bc-account-integrations}.
2. {btn-create}
3. include::ROOT:partial$ui-interactions/enter-integration-name.adoc[]
4. From the *External system* drop-down menu, select *Sikom*.
5. {btn-save}

[#set-up-your-sikom-integration]
== Set up your Sikom integration
1. Install and connect xref:acd-integration:install-cloud-link.adoc[Cloud Link]. During the installation, your terminal shows a PIN that you need to enter in the integrations page to proceed. The PIN expires after 5 minutes.
2. In the *Credentials* section, set up your integration:
   - *Host* and *Port*: Enter the host and port of your database.
   - *Username* and *Password*: Enter valid credentials for a database user with read access to the CCMData database.
3. In the *Configuration* section:
   - Enter the *Database time zone*.
   - Check the *Import agent status data* checkbox to import agent status data from Sikom.

4. {btn-save}

The integration starts importing data. To successfully import agent status data, you first need to xref:acd-integration:import-agent-status-data.adoc#map-external-identifiers-to-people-in-peopleware[map external user identifiers and activities].

[#edit-a-sikom-integration]
== Edit a Sikom integration
In case any of the integration details change, e.g. database server credentials, you can edit and update the configuration of your integration. The data import will continue using the updated configuration.