= Avaya CMS
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn how to connect your Avaya database to import data.
:related-articles: how-integrations-work.adoc, install-cloud-link.adoc, import-agent-status-data.adoc

An Avaya CMS integration is an on-premise integration that imports call and agent status data.

The integration uses xref:acd-integration:install-cloud-link.adoc[Cloud Link].

include::help-center:acd-integration:partial$integration-intro.adoc[]

[#add-an-avaya-cms-integration]
== Add an Avaya CMS integration
1. Go to menu:Account[Integrations].
2. Click btn:[Create].
3. Enter a unique name for the new integration that identifies the data source.
4. From the **External system** drop-down menu, select **Avaya**.
5. Click btn:[Save].

[#set-up-your-new-avaya-cms-integration]
== Set up your new Avaya CMS integration
1. Install and connect xref:acd-integration:install-cloud-link.adoc[Cloud Link]. During the installation, your terminal shows a PIN that you need to enter in the integrations page to proceed. The PIN expires after 5 minutes.
2. In the **Configuration** section, set up your integration:
   - **Connection string**: Enter a xref:#connection-string[connection string] with the specific parameters for your database type and ODBC driver to connect to your Avaya CMS database.
   - **Database time zone**.
   - **Import detailed agent statuses**: Check this checkbox to add information about skills (agent profile) and splits (call routing) to imported agent statuses.
   - **Import real-time agent status data**: Check this checkbox to import agent status data in real time. In this case, enter a port number in the field below.
   - **Port**: Cloud Link will open a listening TCP socket on the specified port. The Avaya Generic RTA service will connect to this port and start streaming real-time agent status data. The Avaya Generic RTA service is licensed and configured in Avaya.

3. Click btn:[Save].

The integration starts importing data. To import agent status data, you need to xref:acd-integration:import-agent-status-data.adoc[map external user identifiers and activities] once your Avaya integration is set up. If you have activated the **Import real-time data** option before, pause your integration.

[#connection-string]
== Connection string
The Avaya CMS integration needs the connection string to connect to your Avaya CMS database. Because Avaya CMS typically uses an IBM Informix database, you need to use a special connection string.

Connection string examples that use the IBM Informix ODBC Driver:<br>

- `DRIVER={IBM INFORMIX ODBC DRIVER};SERVER=myServerAddress;DATABASE=myDatabase;HOST=myHost;SERVICE=myService;UID=myUsername;PWD=myPassword;PROTOCOL=onsoctcp;DELIMIDENT=y;` (native access via ODBC driver)
- `DSN=AvayaCMS;DELIMIDENT=y;` (requires an ODBC connection named AvayaCMS)
  If your Avaya CMS does not use an IBM Informix database, you need to obtain the appropriate connection string for your specific database type and ODBC driver. Avaya only supports ODBC connectivity.

[#edit-an-avaya-cms-integration]
== Edit an Avaya CMS integration
In case any of the integration details change, e.g. database server credentials, you can edit and update the configuration of your integration. The data import will continue using the updated configuration.