= Import data via a CSV integration manually
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Find out how to manually import a CSV file via a CSV integration.
:related-articles: csv-schemas.adoc, add-csv-integration.adoc

This article explains how to manually import a CSV file via a CSV integration.

CSV integrations import data to Peopleware automatically and regularly from a remote folder.
Use a CSV integration's manual import option to provide data ad-hoc to workloads that are set up to receive data via that CSV integration.
Manual imports do not need an active Cloud Link or SFTP connection.

[#prerequisites]
== Prerequisities
- The CSV integration you want to use to import the CSV file is set up.
- The CSV import file matches one of the CSV schemas available in your Peopleware system.
- The CSV file does not exceed the following limits:
  - File size: 10 MB
  - Number of rows: 20000
- Your role has the **Configure Integrations** permission.

[#steps]
== Steps
1. Go to _Account > Integrations_{:.breadcrumbs}
2. In the **Current integrations** overview, find the CSV integration entry you want to use for the upload.
3. Click the {icon-edit} Edit icon. Peopleware opens the integration's details page.
4. Go to the **Manually upload data** section.
5. Click _Upload CSV_{:.doc-button}. Peopleware opens the **CSV Upload** window.
6. If necessary, change the CSV schema to match your CSV import file. By default, Peopleware selects the CSV schema assigned to the CSV integration.
7. Use the upload facility to submit the CSV import file.
8. Click _Import_{:.doc-button}.

Peopleware imports the file and distributes the data to all workloads that are set up to receive data via the CSV integration.