= Import data with Peopleware API
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Add an Peopleware API integration to import contact and agent status data from your external system.
:related-articles: create-workloads.adoc, manage-dashboards.adoc
:page-aliases: import-data-with-injixo-api

We offer vendor-specific and universal integrations to import contact and agent status data from external systems.

[#what-is-an-peopleware-api-integration]
== What is an Peopleware API integration?
In Advanced and Enterprise WFM, Peopleware API integrations allow you to send API requests to import data (e.g. when there is no standard integration for your external system). For this purpose, the Peopleware API provides the following resources:

- [Contact Event resource](https://api.peopleware.com/resources/contact-store/contact-events): Contact events are recorded when customers contact your company via call, email, or chat. This data is stored in queues grouped by queue name and channel.
- [Queue resource](https://api.peopleware.com/resources/queue-store/queues): Queues group historical data by interval and channel. This data is used for forecasting and scheduling.
- [Agent Status resource](https://api.peopleware.com/resources/agent-status-store/agent-status): Agent status data is recorded when employees switch from one activity to the next, e.g. login, wrap-up time, or logout.

[NOTE]
====
The Contact Event resource and the Queues resource should not be used in parallel to send data for the same queue. This will result in data corruption and may cause data loss.
====
[#add-a-peopleware-api-integration]
== Add a Peopleware API integration
Users with admin access can add a Peopleware API integration as follows:

1. Go to {bc-account-integrations}.
2. {btn-create}
3. include::ROOT:partial$ui-interactions/enter-integration-name.adoc[]
4. From the **External system** drop-down menu, select **Peopleware API**.
5. {btn-save}

[#set-up-your-peopleware-api-integration]
== Set up your Peopleware API integration
1. In the **API access** section, click btn:[Generate].

Authentication also works with personal access tokens that have been created in user profiles in the xref:reporting:api.adoc#authorization-personal-access-token[**Personal access tokens**] section.

[NOTE]
====
You cannot access the API key again later.
====
>
[NOTE]
====
- Store the API key in a safe place, e.g. your password manager.
- The current API key expires if any user generates a new API key for the integration or deletes the integration.
====
== Import data <a id="import-contact-or-agent-status-data">

To identify the API integration and to authenticate, include the Peopleware key and the integration ID in API requests:

1. Add your Peopleware key to the Authorization request header.
2. Find or copy your integration ID:
   - {nav-to-account-integrations}
   - Select your API integration section.
   - In the **API Access** section, click the Copy icon \_{icon-clone} next to the integration ID.
3. Add your integration ID to the **meta** object in the request body.

To import data from your external system regularly, you need to run your own application. For sample scripts in Ruby and Python, check the user guides in the [Peopleware API documentation](https://api.peopleware.com).

[#testing-data-imports]
== Testing data imports
For testing, you can send single POST requests to the API. The data array in the examples below contains a single data point but you can change it if needed. Replace at least the sample API key (abc123456=) and the integrationConfigurationId value (1234) with your own.

The API only supports HTTPS. Send your requests to https://api.peopleware.com to avoid `not_found` errors.

[#curl-on-the-command-line]
=== cURL on the command line
The following examples show how to send data to the API using [cURL](https://curl.se/). cURL is a command line tool that exchanges data with a server through a terminal.

Contact events:

----
curl -X POST \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer abc123456=" \
 -d '{"data":[{"properties":{"offered":true,"handled":false,"duration":124.6},"queueName":"Level 1 support","queueIdentifier":"1337_99","timestamp":"2021-12-06T10:34:22Z","channel":"calls"}],"meta":{"integrationConfigurationId":1234}}' \
 https://api.peopleware.com/external-systems/contact-events
----

Note: Each new combination of `queueIdentifier`, `queueName`, and `integrationConfigurationId` will create a new queue. To avoid duplicate queue names, make sure you add the same `queueIdentifier` or the same `integrationConfigurationId` for each request with the same queue name.

Agent status:

----
curl -X POST \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer abc123456==" \
 -d '{"data":[{"agentIdentifier":"bob@mycompany.com","activityIdentifier":"Test","startTime":"2021-12-06T10:00:00Z","endTime":"2021-12-06T15:00:00Z"}],"meta":{"integrationConfigurationId":8431,"externalSystem":"My ACD"}}' \
 https://api.peopleware.com/external-systems/agent-statuses
----

[#rest-clients]
=== REST clients
The following examples show how to send data to the API using a REST client, such as [Postman](https://www.postman.com/downloads/).

1. Include a JSON request header:

   ```
   {
     "Content-type": "application/json",
     "Authorization": "Bearer abc123456="
   }
   ```

2. Include a different JSON request body for contact events and agent status data.<br><br>

   Example request body for contact events: `/external-systems/contact-events`:

   ```
   {
     "data": [
       {
         "properties": { "offered": true, "handled": false, "duration": 124.6 },
         "queueName": "Level 1 support",
         "queueIdentifier": "1337_99",
         "timestamp": "2021-12-06T10:34:22Z",
         "channel": "calls"
       },
       {
         "properties": { "offered": true, "handled": true, "duration": 200.1 },
         "queueName": "Level 1 support",
         "queueIdentifier": "1337_99",
         "timestamp": "2021-12-06T10:46:22Z",
         "channel": "calls"
       }
     ],
     "meta": { "integrationConfigurationId": 1234 }
   }
   ```

   Example request body for agent status: `/external-systems/agent-statuses`:

   ```
   {
     "data": [
       {"agentIdentifier":"bob@mycompany.com","activityIdentifier":"Test","startTime":"2022-12-06T08:00:00Z","endTime":"2022-12-06T13:00:00Z"},
       {"agentIdentifier":"bob@mycompany.com","activityIdentifier":"Test","startTime":"2022-12-07T09:00:00Z","endTime":"2022-12-07T10:00:00Z"}
     ],
     "meta": {
       "integrationConfigurationId": 1234,
       "externalSystem": "My ACD"
     }
   }
   ```

[#your-first-api-request-what-next]
== Your first API request - what next?
After you have sent a successful API request, you need to wait before you can see data in Peopleware. You can work with the imported data as follows:

- Contact events requests: In **Forecast**, the **New workload** and **Edit workload** pages will display the imported queues when data has been processed.
- Agent status data requests: The first request with new agent IDs will not result in actual agent status data in Shift Center. To see data, xref:acd-integration:import-agent-status-data.adoc#map-external-identifiers-to-people-in-peopleware[map at least one external identifier] (sent as agentIdentifier) to a person. You need to send another request to display the data.