= Generate suggestions for group meetings
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Generate scheduling suggestions for group meetings with reduced impact on the coverage of your schedule in Plan > Meetings.
:page-aliases: group-meetings

In *Plan > Meetings*, you can generate scheduling suggestions for group meetings with reduced impact on the coverage of your schedule. Group meetings are meetings with a group of participants and may include a meeting host, typically a team leader.

New to Meetings? Learn xref:scheduling:meetings-overview.adoc[the basics] first.

[#prerequisites]
== Prerequisites
- You have created xref:administration:activities.adoc#create-an-activity[a meeting activity] for group meetings.
- You have created xref:administration:activity-types-and-properties.adoc#activity-properties[Replaceable activities].
- If you want to include a meeting host with a schedule, xref:administration:create-and-manage-planning-units.adoc[the planning units] of the meeting host and the other participants must have the same interval.

[#generate-suggestions-for-group-meetings]
== Generate suggestions for group meetings
1. In {bc-plan-meetings}, click btn:[Set up] in the *Group meetings* tile.
2. In the *Settings* section, configure the following fields:
   - *Planning unit*
   - *Activity to schedule*: Select the meeting activity you created for group meetings.
   - *Date range*
   - *Meeting duration*

3. (Optional) To set the days and time in which meeting suggestions can be generated, activate the *Set additional availability constraint* toggle.
   - *Day*
   - *From* and *To*
   - To add a period in which the meetings could take place on the selected day, click btn:[+ Add time span]. To delete a period, click the {icon-x} next to it.
   - To add more days on which the meetings could take place, click btn:[Add day and time span]. To delete a day, click btn:[{icon-delete} Remove day] next to it.

4. In the *Host* section, select one option:
   - *No host*: You do not want to include a meeting host. The generated suggestions for group meetings may overlap.
   - *Internal host*: You want to include a meeting host that has a schedule. Group meeting suggestions are based on the meeting host's availability. To select the meeting host, use the *Planning unit* and *Employee* drop-down menus.
   - *External host*: You want to include a meeting host that does not have a schedule. Group meeting suggestions are based on the days and periods that you set with the *Set additional availability constraint* toggle.

5. In the *Participants* section, select the people for whom you want to generate meeting suggestions. By default, all people assigned to the selected planning unit are displayed and pre-selected:
   - (Optional) Click the {icon-schedules-filter-employees-u} or the {icon-filter-u} to filter out people. By default, all checkboxes are checked.
   - Uncheck the checkboxes next to the names of people for whom you do not want to generate meeting suggestions. Uncheck the checkbox next to *Name* to deselect all people in the list.

6. (Optional) To generate meetings suggestions for different groups of participants, based on their availabilities, activate the *Split the meeting into several time slots* toggle. You can select the minimum number of people from the *Minimum amount of participants per time slot* drop-down menu.
7. Click btn:[Generate suggestions].

You are redirected to the *Meetings* page and the generated suggestions for group meetings are displayed in the *Generated suggestions* table. You can proceed to xref:scheduling:scheduling-suggestions.adoc[review and apply the meeting suggestions].