= Generate suggestions for 1:1 meetings
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Generate scheduling suggestions for one-on-one meetings with reduced impact on the coverage of your schedule in Plan > Meetings.
:page-aliases: one-on-ones

In {bc-plan-meetings}, you can generate scheduling suggestions for one-on-one meetings (1:1 meetings) with reduced impact on the coverage of your schedule. 1:1 meetings are meetings between a meeting host, typically a team leader, and another team member.

New to Meetings? Learn xref:scheduling:meetings-overview.adoc[the basics] first.

[#prerequisites]
== Prerequisites
- You have created xref:administration:activities.adoc#create-an-activity[a meeting activity] for 1:1 meetings.
- You have created xref:administration:activity-types-and-properties.adoc#activity-properties[Replaceable activities].
- If the meeting host is scheduled, xref:administration:create-and-manage-planning-units.adoc[the planning units] of the meeting host and the other participants must have the same interval.

[#generate-suggestions-for-11-meetings]
== Generate suggestions for 1:1 meetings
To generate suggestions for 1:1 meetings, follow these steps:

1. In {bc-plan-meetings}, click btn:[Set up] in the *1:1 meetings* tile.
2. In the *Settings* section, configure the following fields:
   - *Planning unit*
   - *Activity to schedule*: Select the meeting activity you created for 1:1 meetings.
   - *Date range*
   - *Meeting duration*

3. (Optional) In the *Optional settings* section, check the checkboxes to activate and configure the following fields:
   - *Ensure a buffer between meetings*: Minimum period between meetings in minutes.
   - *Limit the number of meetings per day to maximum*
   - *Consider only time slots for which the resulting coverage will be at least*: Enter the minimum value under which coverage may not drop when scheduling 1:1 meetings.

4. In the *Meeting to be scheduled between* section, define when the meeting host is available for the meeting:
   - If the meeting host does not have a schedule, select btn:[Enter manually] under *Meeting host* and configure the following fields:
     - *Day*
     - *From* and *To*
     - (Optional) Click btn:[+ Add time span] to add a period in which the meeting host is available for 1:1 meetings on the configured day. Click the {icon-x} to delete the period.
     - (Optional) Click btn:[Add day and time span] to add more days in which the meeting host is available for 1:1 meetings. Click btn:[{icon-delete} Remove day] to delete additional days.

   - If the meeting host has a schedule, select btn:[Choose employee] under *Meeting host* and configure the following fields:
     - *Planning unit*
     - *Employee*

5. In the *Participants* section, select the people for whom you want to generate 1:1 meeting suggestions. By default, all people assigned to the selected planning unit are displayed and pre-selected:
   - (Optional) Click the {icon-schedules-filter-employees-u} or the {icon-filter-u} to filter out people. By default, all checkboxes are checked.
   - Uncheck the checkboxes next to the names of people for whom you do not want to generate meeting suggestions. Uncheck the checkbox next to *Name* to deselect all people in the list.

6. Click btn:[Generate suggestions].

You are redirected to the *Meetings* page and the generated suggestions for 1:1 meetings are displayed in the *Generated suggestions* table. You can proceed to xref:scheduling:scheduling-suggestions.adoc[review and apply the meeting suggestions].