// tag::one[]
== First section
Fair t' middlin, this is. Yer couldn't organise a set of fat bobbies. Aye up, she's a reight bobby dazzler. He's a wrong'un like, Theers nowt s'queer as folk.

// end::one[]

// tag::two[]
== Second section
Tha's getten tha'self in a pickle there lass. You're in luck m'boy! I've got nowt to do today, I need summat to do. Oh aye! Aye up, she's a reight bobby dazzler.

// end::two[]

// tag::three[]
== Third section
Fair t' middlin, this is. Yer flummoxed. He's a wrong'un like, Now then, do as thy says, not as thy does. I'm off down't road, I'm flaggin'. Aye, 'is as daft as a brush, lad! 'i couldn't organise a piss up in a brewery. He's a wrong'un like, Were ya born in a barn, lad?

// end::three[]

// tag::four[]
== Fourth section

If in doubt-do nowt! I allus wash behind mi lugholes. Ee bye ecky thump! Ee, stop yer faffing about, lass! Tha meks a better door than a winder. Aye up, she's a reight bobby dazzler. Do I 'eckers like, Am proper knackered, aye I am that is I say. Now then, as it 'appens it's o'er yonder! By eckers, well, I'll go to't foot of't stairs!

// end::four[]
