= Bid on shifts
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to bid on shifts
:related-articles: schedules-shift-bidding.adoc
:page-aliases: bid-on-shifts

Shift bidding allows you to take part in the scheduling process by expressing your shift preferences.

[#prerequisites]
== Prerequisites
- You have been given access to the shift bidding functionality by a user with Admin access.
- A scheduling period with the status Shift bidding enabled has been created by your planner.

For scheduling periods with the status Shift bidding enabled created by your planner, you will see a notification in the Notices section in menu:Me[Dashboard], and a banner in menu:Me[My Calendar].

[#bid-on-shifts]
== Bid on shifts
1. In menu:Me[Dashboard], click btn:[Bid] in a shift bidding notification.  
   A dialog window opens.
2. Select a week from the drop-down menu, then a day.  
   You will see the available shifts for that day.

   > Note
   >
   > You can only bid on shifts up to 100 days in advance. Even if a corresponding scheduling period exists, you will see a message that no shifts are available on days more than 100 days in the future.

3. Under **Choice**, click btn:[1] next to your preferred shift. To add a second choice, click btn:[2] next to another shift.  
   You can place up to two bids on each day. Everyone can bid on the same shifts.  
   You can see how many shifts are needed on each day (Required) and how many times your colleagues have already bid on a specific shift (Requested).

[#why-cant-i-see-shifts-to-bid-on]
== Why can't I see shifts to bid on?
You cannot see shifts to bid on if the following applies to your shift request:

- It would violate contractual working times (e.g. part-timers do not see full-time shifts).
- It would violate scheduling rules (e.g. availability in the afternoon, no morning shifts).
- It would exceed the shift requirements defined for this day (e.g. 4 shifts generated but 4 other people already placed a shift bid).

If you need help with shift bidding, get in touch with your supervisor or planner.