= Time-off periods
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: essential, advanced, enterprise
:topic-type-concept:
:description: Learn what time-off periods are and how to work with them.
:related-articles: vacation-entitlement.adoc, vacation-absences-management.adoc, what-are-scheduling-periods.adoc
:page-aliases: features/scheduling/time-off/time-off-periods

include::help-center:ROOT:partial$reusables/time-off-legacy.adoc[]

Time-off periods are time ranges for which people can request time off in Me, e.g. January 2023-December 2024.

Time-off periods only support the activity types Absence, Vacation, and Illness. The activities must be configured as xref:administration:activities.adoc[Requestable in Me] and xref:administration:create-and-manage-planning-units.adoc[assigned to your planning unit]. Create a separate time-off period for each activity that people can use to request time off.

In Me, people can request time off for different reasons, e.g. vacation or illness. People can only create time-off requests for time ranges that are included in a time-off period with the status Published.

Note: To allow people to request time off, go to menu:Me[] in the main navigation and activate the **Time Off Requests** option.

Use xref:scheduling:what-are-scheduling-periods.adoc[scheduling periods] to allow people xref:scheduling:what-are-scheduling-periods.adoc#when-can-people-see-their-schedules[to see their schedules], xref:scheduling:what-are-scheduling-periods.adoc#when-can-people-swap-shifts[exchange shifts], and xref:scheduling:schedules-shift-bidding.adoc[bid on shifts].

[#status]
=== Status
Every time-off period has a status that determines whether it is available for people in Me. You set a status when you create the time-off period, but you can change the status as often as you want to.

[%header, cols="1a,1a,".rstrip(',')]
|===
|Status
|Explanation
|Unpublished
|People cannot see the time-off period or use it to submit time-off requests. Use this status until you are ready for people to see the time-off period and submit time-off requests.
|Published
|People can see the time-off period in Me and use it to submit time-off requests. The time-off period appears in Me with a white background. You cannot set this status if the time-off period has an expired deadline.
|===

[#manage-time-off-periods]
== Manage time-off periods
1. Go to {bc-plan-time-off}.
2. Click btn:[Time-off periods] on the top right.
3. Select a *Planning unit* to filter the list.
4. Optional: Choose a selection and/or an activity.

The list will show the relevant time-off periods divided into two tabs:

- Ongoing: Time-off periods whose date range lies partly or completely in the future.
- Expired: Time-off periods whose date range lies completely in the past.

Both tabs show a table with six columns. The **Inherited from** column is only relevant when a time-off period was created for a parent planning unit. In that case, all child planning units inherit the time-off period and the column shows the name of the parent planning unit.

To sort a column, click the table header. To reverse the sorting order, click again.

[#create-a-time-off-period]
== Create a time-off period
1. Go to {bc-plan-time-off}.
2. Click btn:[Time-off periods] on the top right.
3. Click btn:[Create time-off period] on the top right.
4. Fill in the fields.
   Remember that people can only request time off if you select the status Published.
5. {btn-save}

[#edit-a-time-off-period]
== Edit a time-off period
If you want to change the status of a time-off period

1. Go to {bc-plan-time-off}.
2. Click btn:[Time-off periods] on the top right.
3. To change the status, use the drop-down in the **Status** column. The changed status will be saved automatically.  
   To edit other data, hover over the list item that you want to edit and click the {icon-edit} on the right.
4. Edit the relevant data.
5. {btn-save}

[#delete-a-time-off-period]
== Delete a time-off period
1. Go to {bc-plan-time-off}.
2. Click btn:[Time-off periods] on the top right.
3. Check one or more checkboxes on the left. The checkbox on the header selects all items.
4. Click btn:[Delete entries].