= Download forecasts
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: Alexis Braine
:product-label: advanced, enterprise

In {bc-forecast-workloads}, you can download your forecast data as a CSV file.

You can download forecast data for up to 24 months.
You can download the *Forecast* xref:forecast:save-forecast-versions.adoc#save-a-forecast-version[version data] by itself, or together with any other versions.

[#download-a-forecast]
== Download a forecast

. In {bc-forecast-workloads}, select a workload.
. Select the time frame using the date picker.
Click a week number to select the whole week, or click any day and drag to select a custom period.
. From the context menu icon {icon-context-menu} at the top right, select *Download as CSV*.
. Select the forecast data that you want to download.
+
To select all available versions, check the *All* checkbox.
. Click {btn-download-as-csv}.
+
The downloaded forecast versions are saved in one file.

[#csv-file-example]
== CSV file example

The CSV file name contains the workload name and the channel.
For example, the CSV file for the calls workload Orders is named `Orders-Calls.csv`.
The column headers show the forecast version.
The file contains timestamps formatted as `YYYY-MM-DD` and values for each forecast.
It uses the time zone and interval of the workload.
The file does not include information about public holidays, events added to the workload, or historical data.

If you select *Forecast* and *Operational*, the file looks as follows:

====
----
Timestamp;Offered_auto;AHT_auto;Offered_operational;AHT_operational
...
2020-05-17 16:30;40;180;35;175
2020-05-17 16:45;41;181;37;183
2020-05-17 17:00;40;180;35;175
2020-05-17 17:15;41;181;37;183
...
----
====

[NOTE]
====
The download option is only available for Smart workloads in Live mode.
Switch the workload to Live mode to access the download option.
See xref:forecast:create-workloads.adoc[] for details about Live mode and Test mode.
Smart workloads are only available for Enterprise and Advanced WFM plans.
====

{see-also-title}
* xref:forecast:save-forecast-versions.adoc[]
* xref:forecast:import-forecast.adoc[]
