= Add events and public holidays
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Create events to improve the accuracy of your forecast
:related-articles: create-workloads.adoc
:page-aliases: events-and-holidays

Add events to your historical data and the generated *forecast* to improve the *forecast* results. Besides data, events are the second most important driver for forecast quality.

New to **Forecast**? Learn xref:forecast:what-is-forecast.adoc[the basics] first.

[#what-are-events]
== What are events?
Events allow you to mark past and future days where the contact volume or data deviate from the standard. For example:

- Days with unusually low or high volume or *average handle time* (*AHT*), e.g. due to marketing or newsletter campaigns.
- Days with volume distributions that deviate from a standard day.
- Days with incomplete, faulty, or missing data, e.g. due to an *ACD* outage.

You can create an event and add it to one or more *workloads*. *Forecast* analyzes events to detect trends, fluctuations in volume, and other patterns to improve the generated *forecast*.

Public holidays are created and added to your *workloads* automatically when you select a holiday region in your xref:forecast:create-workloads.adoc#create-workloads[workload's basic configuration]. Public holidays are treated like events because they may influence the contact volume for the day.

[#create-an-event]
== Create an event
1. Go to menu:Forecast[Events].
2. Click btn:[Create event].
3. Enter a **Name**.
4. (Optional) Check the checkbox *Mark as an outlier* if you want to ignore the event from the *forecast*, e.g. because you know that the contact volume or data will not be representative on that day. Leave the checkbox unchecked if you want to use the contact volume or data generated on the day of the event when creating the forecast.
5. Click btn:[Save].<br>
   The event appears in the event list. In the event list, you can see if the event is marked as an outlier, and how many *workloads* it affects.

You can edit the event, e.g. to mark it as an outlier, at any time.

[#add-an-event-to-a-workload]
== Add an event to a *workload*
<!--Add all known events to past and future dates. Omit longer periods with uncommon patterns, as these periods and patterns degrade the quality of the forecast over time.
Smart workloads consider an event's impact up to two days before and after the event date. Basic workloads only consider the event's impact on the actual day. (@Jose, do we still need this here?)-->

You need to add the created events to all relevant *workloads* so that they are considered when calculating the *forecast*.

To add an event to a *workload*, proceed as follows:

1. In menu:Forecast[Workloads], select a *workload*.
2. From the {icon-context-menu} at the top right, select *Manage events*.
3. Click *+ Add event* and enter the relevant information:
   - *Event*: Select an event from the drop-down menu. Outliers are marked with the word Outlier in brackets next to the event name. You can only see events within the date range of the selected workload.
   - *Date range*: Select the date range to which you want to add the event. You can only add events within the *date range* of the selected *workload*.<br>
     You cannot add overlapping events to the same *workload*. If the *date range* of the new event overlaps with an existing event, adjust the dates or remove one of the events.
4. Click btn:[Save].<br>
   The event appears in the window. Events are color-coded. The color code is the same in the *workload* graphs.
5. Click btn:[Close].

[NOTE]
====
====
>
[NOTE]
====
To exclude a past day from the forecast calculation, add an event that is marked as an outlier to the *workload*.
====
[#add-an-event-to-several-workloads]
== Add an event to several *workloads*
<!--Add all known events to past and future dates. Omit longer periods with uncommon patterns, as these periods and patterns degrade the quality of the forecast over time.
Smart workloads consider an event's impact up to two days before and after the event date. Basic workloads only consider the event's impact on the actual day. (@Jose, do we still need this here?)-->

You can add an event to several *workloads* at a time. This makes it easier to manage events across different *workloads*, for example when you work with a large number of *workloads*. To add an event to several *workloads*, proceed as follows:

1. In menu:Forecast[Events], select an event.
2. Next to *Calendar entries*, click *+ Add*.
3. In the *Add calendar entry* window, enter the relevant data:
   - *Date range*: Use the date picker to select the date range to which you want to add the event.
   - *Workloads*: Check the checkboxes next to the workloads to which you want to add the event.

4. Click btn:[Save].

   > Note
   >
   > You can only see *workloads* for which you have edit rights. <!-- add WL permissions link when live -->

[#remove-an-event-from-a-workload]
== Remove an event from a *workload*
To remove an event from a *workload*, proceed as follows:

1. In menu:Forecast[Workloads], select a *workload*.
2. From the {icon-context-menu} at the top right, select *Manage events*.
3. Click the {icon-delete} next to the event you want to remove.
4. Click btn:[Close].
   The *forecast* will be recalculated.<!--Is this true?-->

[#remove-an-event-from-several-workloads]
== Remove an event from several *workloads*
To remove an event from several *workloads*, proceed as follows:

1. In menu:Forecast[Events], select an event.
2. In the *Calendar entries* section, select a calendar entry.
3. Uncheck the checkboxes next to the *workloads* from which you want to remove the calendar entry.<br>
   Removing the calendar entry from all *workloads* removes the calendar entry from the list but does not delete the event.
4. Click btn:[Save].

[#delete-an-event]
== Delete an event
If you no longer need an event, you can delete it. Proceed as follows:

1. In menu:Forecast[Events], hover over an event in the list.
2. Click the {icon-delete} on the right of the entry.
3. In the confirmation window, click btn:[Delete].

[WARNING]
====
====
>
[NOTE]
====
If you delete an event, it will be deleted from all affected *workloads* and generated *forecasts*. The *forecast* will be recalculated.
====
[#change-the-holiday-region]
== Change the holiday region
When you xref:forecast:create-workloads.adoc#create-workloads[create a workload], you can select a holiday region to automatically add the public holidays from that region to your *workload* as events.

To change the holiday region and associated public holiday events, proceed as follows:

1. In menu:Forecast[Workloads], select a *workload*.
2. Click btn:[Edit] at the top right.
3. Select a **Holiday region** from the drop-down menu.
4. Click btn:[Save workload].

[#see-events-and-public-holidays-in-the-workload-graphs]
== See events and public holidays in the *workload* graphs
In the *workload* graphs in menu:Forecast[Workloads], you can identify events, events marked as outliers, and public holidays by color. You can see which color is used for which event in the graph legend.

1. In menu:Forecast[Workloads], select a *workload*.
2. Select a time period from the date picker. Click on a week number to select the whole week, or click any day and drag to select a period shorter or longer than a week.
3. Hover over the graphs to see events, events marked as outliers, and public holidays.