= Add events and public holidays
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Create events to improve the accuracy of your forecast
:related-articles: create-workloads.adoc
:page-aliases: events-and-holidays

Add events to your historical data and the generated _forecast_{:.css} to improve the _forecast_{:.css} results. Besides data, events are the second most important driver for forecast quality.

New to **Forecast**? Learn xref:forecast:what-is-forecast.adoc[the basics] first.

[#what-are-events]
== What are events?
Events allow you to mark past and future days where the contact volume or data deviate from the standard. For example:

- Days with unusually low or high volume or _average handle time_{:.css} (_AHT_{:.css}), e.g. due to marketing or newsletter campaigns.
- Days with volume distributions that deviate from a standard day.
- Days with incomplete, faulty, or missing data, e.g. due to an _ACD_{:.css} outage.

You can create an event and add it to one or more _workloads_{:.css}. _Forecast_{:.css} analyzes events to detect trends, fluctuations in volume, and other patterns to improve the generated _forecast_{:.css}.

Public holidays are created and added to your _workloads_{:.css} automatically when you select a holiday region in your xref:forecast:create-workloads.adoc#create-workloads[workload's basic configuration]. Public holidays are treated like events because they may influence the contact volume for the day.

[#create-an-event]
== Create an event
1. Go to _Forecast > Events_{:.breadcrumbs}.
2. Click _Create event_{:.doc-button}.
3. Enter a **Name**.
4. (Optional) Check the checkbox _Mark as an outlier_{:.label} if you want to ignore the event from the _forecast_{:.css}, e.g. because you know that the contact volume or data will not be representative on that day. Leave the checkbox unchecked if you want to use the contact volume or data generated on the day of the event when creating the forecast.
5. Click _Save_{:.doc-button}.<br>
   The event appears in the event list. In the event list, you can see if the event is marked as an outlier, and how many _workloads_{:.css} it affects.

You can edit the event, e.g. to mark it as an outlier, at any time.

[#add-an-event-to-a-workload]
== Add an event to a _workload_{:.css}
<!--Add all known events to past and future dates. Omit longer periods with uncommon patterns, as these periods and patterns degrade the quality of the forecast over time.
Smart workloads consider an event's impact up to two days before and after the event date. Basic workloads only consider the event's impact on the actual day. (@Jose, do we still need this here?)-->

You need to add the created events to all relevant _workloads_{:.css} so that they are considered when calculating the _forecast_{:.css}.

To add an event to a _workload_{:.css}, proceed as follows:

1. In _Forecast > Workloads_{:.breadcrumbs}, select a _workload_{:.css}.
2. From the {icon-context-menu} at the top right, select _Manage events_{:.label}.
3. Click _+ Add event_{:.label} and enter the relevant information:
   - _Event_{:.label}: Select an event from the drop-down menu. Outliers are marked with the word Outlier in brackets next to the event name. You can only see events within the date range of the selected workload.
   - _Date range_{:.label}: Select the date range to which you want to add the event. You can only add events within the _date range_{:.css} of the selected _workload_{:.css}.<br>
     You cannot add overlapping events to the same _workload_{:.css}. If the _date range_{:.css} of the new event overlaps with an existing event, adjust the dates or remove one of the events.
4. Click _Save_{:.doc-button}.<br>
   The event appears in the window. Events are color-coded. The color code is the same in the _workload_{:.css} graphs.
5. Click _Close_{:.doc-button}.

[NOTE]
====
====
>
[NOTE]
====
To exclude a past day from the forecast calculation, add an event that is marked as an outlier to the _workload_{:.css}.
====
[#add-an-event-to-several-workloads]
== Add an event to several _workloads_{:.css}
<!--Add all known events to past and future dates. Omit longer periods with uncommon patterns, as these periods and patterns degrade the quality of the forecast over time.
Smart workloads consider an event's impact up to two days before and after the event date. Basic workloads only consider the event's impact on the actual day. (@Jose, do we still need this here?)-->

You can add an event to several _workloads_{:.css} at a time. This makes it easier to manage events across different _workloads_{:.css}, for example when you work with a large number of _workloads_{:.css}. To add an event to several _workloads_{:.css}, proceed as follows:

1. In _Forecast > Events_{:.breadcrumbs}, select an event.
2. Next to _Calendar entries_{:.label}, click _+ Add_{:.label}.
3. In the _Add calendar entry_{:.label} window, enter the relevant data:
   - _Date range_{:.label}: Use the date picker to select the date range to which you want to add the event.
   - _Workloads_{:.label}: Check the checkboxes next to the workloads to which you want to add the event.

4. Click _Save_{:.doc-button}.

   > Note
   >
   > You can only see _workloads_{:.css} for which you have edit rights. <!-- add WL permissions link when live -->

[#remove-an-event-from-a-workload]
== Remove an event from a _workload_{:.css}
To remove an event from a _workload_{:.css}, proceed as follows:

1. In _Forecast > Workloads_{:.breadcrumbs}, select a _workload_{:.css}.
2. From the {icon-context-menu} at the top right, select _Manage events_{:.label}.
3. Click the {icon-delete} next to the event you want to remove.
4. Click _Close_{:.doc-button}.
   The _forecast_{:.css} will be recalculated.<!--Is this true?-->

[#remove-an-event-from-several-workloads]
== Remove an event from several _workloads_{:.css}
To remove an event from several _workloads_{:.css}, proceed as follows:

1. In _Forecast > Events_{:.breadcrumbs}, select an event.
2. In the _Calendar entries_{:.label} section, select a calendar entry.
3. Uncheck the checkboxes next to the _workloads_{:.css} from which you want to remove the calendar entry.<br>
   Removing the calendar entry from all _workloads_{:.css} removes the calendar entry from the list but does not delete the event.
4. Click _Save_{:.doc-button}.

[#delete-an-event]
== Delete an event
If you no longer need an event, you can delete it. Proceed as follows:

1. In _Forecast > Events_{:.breadcrumbs}, hover over an event in the list.
2. Click the {icon-delete} on the right of the entry.
3. In the confirmation window, click _Delete_{:.doc-button}.

[WARNING]
====
====
>
[NOTE]
====
If you delete an event, it will be deleted from all affected _workloads_{:.css} and generated _forecasts_{:.css}. The _forecast_{:.css} will be recalculated.
====
[#change-the-holiday-region]
== Change the holiday region
When you xref:forecast:create-workloads.adoc#create-workloads[create a workload], you can select a holiday region to automatically add the public holidays from that region to your _workload_{:.css} as events.

To change the holiday region and associated public holiday events, proceed as follows:

1. In _Forecast > Workloads_{:.breadcrumbs}, select a _workload_{:.css}.
2. Click _Edit_{:.doc-button} at the top right.
3. Select a **Holiday region** from the drop-down menu.
4. Click _Save workload_{:.doc-button}.

[#see-events-and-public-holidays-in-the-workload-graphs]
== See events and public holidays in the _workload_{:.css} graphs
In the _workload_{:.css} graphs in _Forecast > Workloads_{:.breadcrumbs}, you can identify events, events marked as outliers, and public holidays by color. You can see which color is used for which event in the graph legend.

1. In _Forecast > Workloads_{:.breadcrumbs}, select a _workload_{:.css}.
2. Select a time period from the date picker. Click on a week number to select the whole week, or click any day and drag to select a period shorter or longer than a week.
3. Hover over the graphs to see events, events marked as outliers, and public holidays.