= Activate business hours
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to activate business hours and how they affect the forecast behavior.
:related-articles: what-is-forecast.adoc, create-workloads.adoc
:page-aliases: forecast-activate-business-hours

New to *Forecast*? Learn xref:forecast:what-is-forecast.adoc[the basics] first.

By default, workloads do not take business hours into account, and forecasts are based on the total daily volume. You can configure workloads so that business hours are taken into account and displayed in the forecast. Staff requirements always take business hours into account by default.

The Classic plan supports business hours only in Smart workloads.

[#prerequisites]
== Prerequisites
{prereq-intro}

- You have configured valid xref:administration:create-and-manage-planning-units.adoc#add-business-hours[business hours] and xref:administration:activities.adoc[activities] for the planning unit for which you want to activate business hours.
- You have checked the xref:administration:set-a-validity-period.adoc[*Valid from*/*Valid to*] entries for the planning unit and activity assigned to the workload and removed or changed them, if necessary.
- You have the necessary permissions to view and edit the relevant planning units.
- If there is a planning calendar assigned to the planning unit, you also have the necessary xref:account:configure-user-roles.adoc#set-wfm-permissions[permissions] for the planning calendar to display the business hours.

[#activate-business-hours]
== Activate business hours
To include volumes outside business hours into the forecast calculation, activate business hours separately for each workload.

1. {nav-to-forecast-workloads}
2. {btn-edit}
3. In the *Basic configuration* section, select a planning unit and an activity.
4. Check the *Forecast within business hours only* checkbox. +
If you update the planning unit's business hours, uncheck and check the checkbox again to update the forecast.
5. Click btn:[Save workload].
   A new forecast is calculated. The calculation can take some time.

Once you have activated the business hours, the graph on the *Forecast* page displays periods outside business hours as gray areas.

[NOTE]
====
Forecasts and staff requirements are generated only if the xref:administration:create-and-manage-planning-units.adoc#add-business-hours-[business hours] and the xref:administration:create-and-manage-planning-units.adoc#add-activities-[activity] configured for the workload specify date and time values that apply to the forecasting period.
====
[#effects-on-the-forecast]
== Effects on the forecast
Activating business hours in a workload has the following effects:

- Business hours are read from the planning unit and activity assigned to the workload. Peopleware only displays the times when both the planning unit and the workload are simultaneously open as business hours. Any interval within this period is considered and displayed as open in the forecast graph.
- Volumes outside of the business hours are redistributed within the business hours. The total daily volume does not change. The distribution is relative to existing interval values and thus follows the forecasted intraday pattern. Volumes outside of business hours become 0.
- Any forecasted average handling time values outside business hours are set to 0.