= Import forecasts
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Learn how to import a forecast from an external source.
:related-articles: create-workloads.adoc
:page-aliases: import-forecast

You can import CSV files with forecasted contact volume and AHT data generated outside Peopleware.

New to *Forecast*? Learn xref:forecast:what-is-forecast.adoc[the basics] first.

[#prerequisites]
== Prerequisites
To import a forecast, you need the following:

- A xref:forecast:create-workloads.adoc[workload].
  If you want to import forecasts only, a workload without queues that does not require any integration may be the right option.
- A CSV file with contact data that contains at least one row for a single interval, e.g.:

----
Timestamp;Offered;AHT
2024-13-09 08:15;14;192
----

[NOTE]
====
You cannot import one single daily value, but interval data is required.
====
[#import-data-requirements]
=== Import data requirements
Your import data must match the format requirements specified by the CSV schema you use for the import.
Peopleware provides a default template for forecast imports. For more information see xref:general:csv-schema-default-schemas.adoc#forecast[Default CSV schemas].

In addition to the format requirements specified by the CSV schema, the CSV import file must fulfill the following requirements:

- Timestamps match the workload's timezone.
- Timestamps of individual records yield full hour, half-hour, or quarterly hour intervals. The interval must match the workload's interval configuration.
- Volume data is provided as integer values, e.g. `00`.
- AHT data is provided as integer values or decimal values (e.g. `180.5`).
- The maximum file size is 20 MB or 20.000 rows.
- The maximum date range is 1 year.

[NOTE]
====
When the AHT column is not included or values are 0, Forecast may unable to calculate staff requirements with certain calculation methods. However, you can still use a fixed value to overwrite the imported AHT.
====
[#handle-import-data-gaps]
=== Handle import data gaps
Peopleware can handle CSV import files with missing rows or partial ones.

In the Volume and AHT graph, missing data is displayed as 0.
New data overwrites existing data for matching timestamps.
Intervals with data gaps retain the original workload data.

Example: Row with partially missing data

----
Timestamp;Offered;AHT
2025-05-17 15:00;30;210
2025-05-17 15:15;;
2025-05-17 15:30;40;180
----

Example: Missing row (15-minute interval)

----
Timestamp;Offered;AHT
2025-05-17 15:00;30;210
2025-05-17 15:30;40;180
----

[#import-a-forecast]
== Import a forecast
1. In {bc-forecast-workloads}, select the workload for which you want to import the external forecast data.
2. From the three-dot menu {icon-context-menu} at the top right, select *Import forecast data*.
3. In the CSV schema field, select the CSV schema you want to use to import the data.
4. Provide the CSV file in the upload dialog.
5. Click btn:[Import].
6. Wait for the upload to complete.
7. Click btn:[Close]

Depending on the CSV schema settings, Peopleware displays the imported forecast data as *Imported forecast* or a forecast version in the volume or AHT graph.
If you don't see the import data, make sure the data period set for the page covers a period for which you have imported data.