= Configure workload permissions
include::help-center:ROOT:partial$libs/libs.adoc[]
:author: 
:email: 
:product-label: advanced, enterprise
:topic-type-concept:
:description: Define permissions to view, create, edit, and delete workloads, as well as to edit forecasts and staff requirements calculation.
:related-articles: create-workloads.adoc
:page-aliases: workload-permissions

In menu:Account[Roles], you can configure different *permissions* for all *workloads* in **Forecast**, including future *workloads*. This is useful if you want a role to have only view *permissions* for all *workloads*, and other roles to have both view and edit *permissions* for all *workloads*.

New to **Forecast**? Learn xref:forecast:what-is-forecast.adoc[the basics] first.

[#configure-workload-permissions]
== Configure *workload permissions*
1. Go to menu:Account[Roles].
2. Select the role for which you want to edit *workload permissions*.
3. Scroll down to *Forecast* and check or uncheck the following checkboxes:
   - *Create workloads*
   - *Access to Requirement Calculations*
4. Click *Configure workload permissions*.
5. In the **General** section, check the relevant checkboxes for all *workloads*.
6. Click *Save changes*.

[#configure-individual-workload-permissions]
== Configure individual workload permissions
In Enterprise WFM, you can also configure *permissions* for individual *workloads*. This allows you to customize view and edit *permissions* to specific *workloads* for specific roles. For example, you might want a group of planners to have view *permissions* only to call *workloads*, and another group of planners to have view *permissions* only to chat *workloads*, while managers have both view and edit *permissions* to all *workloads*.

To configure *permissions* for individual *workloads*, proceed as follows:

1. Go to menu:Account[Roles].
2. Select the role for which you want to edit *workload permissions*.
3. Scroll down to *Forecast* and check or uncheck the following checkboxes:
   - *Create workloads*
   - *Access to Requirement Calculations*
4. Click *Configure workload permissions*.
5. In the **General** section, check the relevant checkboxes for all *workloads*.
6. In the *Workload* section, check the relevant checkboxes for each *workload* individually. Use the search field to narrow down the *workload* list, if necessary.
7. Click *Save changes*.